BEGIN;

-- ── QUIZ QUESTIONS ────────────────────────────────────────────────────────────

INSERT INTO pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES

  -- Checkpoint D1
  ('vietnam-d1-q1', 'vietnam-001', 'checkpoint', 1,
   'A hardworking, compliant student always completes assignments on time and takes meticulous notes, but never volunteers in class discussion and avoids open-ended tasks. What is the strongest first interpretation?',
   $$[
     {"id":"vietnam-d1-q1-a","text":"The student lacks confidence and would benefit from encouragement to participate more.","isCorrect":false,"feedback":"Too quick. This reads the behaviour through a Western confidence lens. The pattern described — visible diligence without intellectual risk-taking — is more consistent with obligation-driven study than personality-based reluctance.","explanation":"This reads the behaviour through a Western confidence lens and misses the filial piety motivation structure."},
     {"id":"vietnam-d1-q1-b","text":"The student is performing the study behaviours that filial piety demands — diligence and compliance — without necessarily being driven by curiosity or personal engagement.","isCorrect":true,"feedback":"Yes. The research on authoritarian filial piety in Vietnamese students shows this pattern: high visible effort driven by family obligation rather than intrinsic motivation. This student may also be carrying a depression risk that the compliance masks.","explanation":"Authoritarian filial piety produces visible diligence that can mask obligation-driven stress rather than genuine engagement."},
     {"id":"vietnam-d1-q1-c","text":"The student is probably performing well in tutoring classes and saving their energy for that context.","isCorrect":false,"feedback":"Possible but not the strongest first reading. While 92.1% of Vietnamese students attend extra classes, the behavioural pattern described points more directly to the filial piety motivation structure than to split academic loyalty.","explanation":"Tutoring is common but the described pattern maps more directly to filial obligation than split attention."},
     {"id":"vietnam-d1-q1-d","text":"The student is introverted and would perform better in written assessments than in class participation.","isCorrect":false,"feedback":"This personalises a culturally structured behaviour. The avoidance of open-ended tasks and class discussion is more likely a face-protection and obligation-performance pattern than a personality trait.","explanation":"Personalising culturally structured behaviour as introversion misses the systemic dynamic."}
   ]$$::jsonb,
   1),

  -- Checkpoint D2
  ('vietnam-d2-q1', 'vietnam-001', 'checkpoint', 2,
   'A parent says: "The school my child attended before gave three worksheets every night. Here there seems to be very little homework. How do I know the school is serious?" What is the strongest first interpretation?',
   $$[
     {"id":"vietnam-d2-q1-a","text":"The parent is resistant to IB pedagogy and prefers a traditional teaching model.","isCorrect":false,"feedback":"Too reductive. The parent is not making a pedagogical argument — they are using the only quality signal they have. Homework volume is a proxy for institutional seriousness in a system where 92.1% of students attend supplementary tutoring.","explanation":"The parent is not resisting IB — they are applying the only quality metric their educational experience provided."},
     {"id":"vietnam-d2-q1-b","text":"The parent is using homework volume as a quality marker because that is the only signal of institutional seriousness they have been trained to read.","isCorrect":true,"feedback":"Yes. In a system where structured academic output is the visible proof of quality education, the absence of homework reads as the absence of rigour — not as a different pedagogical approach. The response is to make your assessment model visible and legible, not to defend the philosophy.","explanation":"Homework volume is a quality proxy trained by the Vietnamese system. The response is to make your approach legible, not to defend a philosophy."},
     {"id":"vietnam-d2-q1-c","text":"The parent is comparing costs and wants to see more visible output to justify the higher fees.","isCorrect":false,"feedback":"Fee consciousness is real, but the concern runs deeper than value-for-money. The parent is asking whether this school produces the kind of academic seriousness that their community recognises.","explanation":"This underestimates the concern. The parent is asking about educational legitimacy, not cost-efficiency."},
     {"id":"vietnam-d2-q1-d","text":"The parent is anxious and needs reassurance that the school has high standards.","isCorrect":false,"feedback":"Partially right but too generic. The specific dynamic is that homework volume is a learned quality marker in Vietnamese education culture — the parent needs their quality framework translated, not their anxiety soothed.","explanation":"Reassurance addresses the symptom; translating the quality framework addresses the cause."}
   ]$$::jsonb,
   2),

  -- Checkpoint D3
  ('vietnam-d3-q1', 'vietnam-001', 'checkpoint', 3,
   'A student never asks a question in class and does not challenge ideas during discussion, but performs well on written assessments. A colleague says: "She clearly understands the material — she just needs to participate more." What does the research say about this pattern?',
   $$[
     {"id":"vietnam-d3-q1-a","text":"The colleague is right — the student understands but needs to build participation habits.","isCorrect":false,"feedback":"This treats silence as a skill deficit. In Confucian-heritage classroom culture, not asking questions and not challenging the teacher is not passive — it is an active performance of respect that protects both the student's and the teacher's face.","explanation":"Silence in a Confucian classroom is an active performance of respect, not a participation deficit."},
     {"id":"vietnam-d3-q1-b","text":"The student's silence is a culturally structured behaviour: asking questions or challenging ideas in class disrupts collective harmony and costs both parties face. The written performance confirms understanding; the silence confirms cultural navigation.","isCorrect":true,"feedback":"Yes. The student is demonstrating competence in two systems simultaneously: the written assessment (academic) and the classroom interaction (cultural). Pushing for more verbal participation without understanding why it feels risky will likely produce rehearsed compliance rather than genuine engagement.","explanation":"The student is navigating two competency systems — academic understanding (written) and cultural performance (classroom behaviour)."},
     {"id":"vietnam-d3-q1-c","text":"The student is probably doing most of her real learning in tutoring and treating school as a social environment.","isCorrect":false,"feedback":"The strong written performance contradicts this reading. The student is clearly learning effectively — the question is about why verbal participation looks different, not about whether learning is happening.","explanation":"Strong written performance directly contradicts the idea that learning is happening elsewhere."},
     {"id":"vietnam-d3-q1-d","text":"The student may have a language barrier that makes verbal participation more difficult than written work.","isCorrect":false,"feedback":"Worth considering but not the strongest first reading for a Vietnamese student in this context. The pattern of strong written work with absent verbal participation maps more directly to face-saving classroom norms than to language proficiency.","explanation":"Language barriers are worth checking but the described pattern maps more directly to Confucian face-saving norms."}
   ]$$::jsonb,
   3),

  -- Checkpoint D4
  ('vietnam-d4-q1', 'vietnam-001', 'checkpoint', 4,
   'A parent asks whether your school''s portfolio assessment is "equivalent to the national curriculum standard." What is the most useful way to hear this question?',
   $$[
     {"id":"vietnam-d4-q1-a","text":"The parent distrusts the IB and wants their child back in the national system.","isCorrect":false,"feedback":"Too adversarial. The parent chose this school. The question is not about leaving — it is about whether the school's assessment produces outcomes that are legible to the world the parent navigates.","explanation":"The parent chose this school. The question is about legibility, not about exit."},
     {"id":"vietnam-d4-q1-b","text":"The parent is asking for reassurance that the school is accredited.","isCorrect":false,"feedback":"Accreditation may be part of it, but the deeper question is about whether the school's assessment currency is recognised in the competitive arena the parent understands — university admissions, community reputation, employability.","explanation":"Accreditation is surface-level. The real question is about competitive legibility."},
     {"id":"vietnam-d4-q1-c","text":"The parent is requesting a translation: they need to understand what the portfolio assessment produces in terms they — and their community — can recognise as legitimate academic evidence.","isCorrect":true,"feedback":"Yes. This is the assessment translation problem. The parent is not rejecting your system — they are asking you to make it legible in the only frame they have. University outcomes data, structured criteria explanations, and explicit connections to recognised academic standards address the real question.","explanation":"The parent needs a translation from portfolio language into the competitive-outcome language their world uses."},
     {"id":"vietnam-d4-q1-d","text":"The parent is comparing your school unfavourably to a competitor and fishing for weaknesses.","isCorrect":false,"feedback":"This reads malicious intent into what is more likely genuine uncertainty. First-generation international school parents in Vietnam have fewer reference points than parents in more established international school markets.","explanation":"Reading malicious intent into genuine uncertainty misses the first-generation dynamic."}
   ]$$::jsonb,
   4),

  -- Checkpoint D5
  ('vietnam-d5-q1', 'vietnam-001', 'checkpoint', 5,
   'A student reveals that she attends a tutoring centre for maths and science three evenings a week alongside her international school day. A colleague says: "That means the parents don''t trust what we''re doing." What is the strongest first interpretation?',
   $$[
     {"id":"vietnam-d5-q1-a","text":"The colleague is probably right — the family is hedging against the school's approach.","isCorrect":false,"feedback":"This frames tutoring as a vote of no-confidence. In a context where 92.1% of students attend extra classes, the decision to enroll in tutoring is normative — not enrolling would feel like reducing investment.","explanation":"In a context where 92.1% attendance is the norm, tutoring is the default, not a signal of distrust."},
     {"id":"vietnam-d5-q1-b","text":"Tutoring is so normalised in Vietnamese education culture (92.1% participation) that the family is fulfilling a standard expectation, not expressing distrust of the school. The real concern is the student's total cognitive load.","isCorrect":true,"feedback":"Yes. The interpretive move is to shift from 'why are they doing this to us?' to 'what is this student carrying?' A student attending tutoring three evenings a week alongside a full school day is operating on a schedule that affects attention, creative capacity, and mental health.","explanation":"The diagnostic question is not 'do they trust us?' but 'what is this student's total load?' — and that load has documented mental health implications."},
     {"id":"vietnam-d5-q1-c","text":"The student is probably performing better in tutoring and may eventually transfer to a more traditional school.","isCorrect":false,"feedback":"This reads the situation as competitive when it is more likely complementary. Vietnamese families typically see tutoring as additional support, not as a replacement pathway.","explanation":"Vietnamese families typically see tutoring as complementary support, not a competing pathway."},
     {"id":"vietnam-d5-q1-d","text":"The parents may not be able to afford the tutoring long-term and should be advised to stop.","isCorrect":false,"feedback":"Advising a Vietnamese family to stop tutoring — particularly from a foreign teacher — risks being heard as the school telling parents they are investing too much in their child's education. This is culturally tone-deaf.","explanation":"Telling a Vietnamese family to reduce educational investment contradicts the filial piety framework and will be heard as dismissive."}
   ]$$::jsonb,
   5),

  -- Checkpoint D6
  ('vietnam-d6-q1', 'vietnam-001', 'checkpoint', 6,
   'A parent says: "Please always tell us what our child needs to improve. We do not need to hear what is going well — we can see that at home." A colleague responds: "That''s quite a negative approach to parenting." What does the research say?',
   $$[
     {"id":"vietnam-d6-q1-a","text":"The colleague is right to be concerned — focusing only on deficits can damage a child's self-esteem.","isCorrect":false,"feedback":"This applies a Western feedback model to a different cultural communication norm. Vietnamese parents are accustomed to hearing what needs to improve as the substantive content of educational feedback. Leading with positives can be read as the teacher avoiding the real conversation.","explanation":"Western feedback norms do not map directly onto Vietnamese educational communication culture."},
     {"id":"vietnam-d6-q1-b","text":"The parent is expressing a culturally normal Vietnamese feedback preference: improvement-focused communication is heard as serious engagement, not negativity. The teacher who leads with positives may actually be undermining trust.","isCorrect":true,"feedback":"Yes. Vietnamese educational culture treats developmental feedback as the serious, respectful part of the conversation. A parent who asks for improvement-focused communication is telling you how to build trust with them — listen to it.","explanation":"In Vietnamese feedback culture, improvement-focused communication signals seriousness and respect. Leading with positives can signal avoidance."},
     {"id":"vietnam-d6-q1-c","text":"The parent is probably anxious about the child's performance and needs data to feel reassured.","isCorrect":false,"feedback":"Partially true but misses the cultural layer. This is not anxiety-driven — it is a communication preference shaped by Vietnamese educational norms. The parent is not asking for reassurance; they are asking for the kind of feedback they consider useful.","explanation":"This is a communication preference, not anxiety. The parent is telling you what format of feedback they consider useful."},
     {"id":"vietnam-d6-q1-d","text":"The parent may be putting too much pressure on the child and the teacher should flag this with pastoral care.","isCorrect":false,"feedback":"Premature. The request for improvement-focused feedback is culturally normative in Vietnam and does not, by itself, indicate harmful parental pressure. Pathologising normal cultural communication risks damaging the parent-teacher relationship.","explanation":"Pathologising a culturally normal communication preference risks damaging the relationship without evidence of harm."}
   ]$$::jsonb,
   6),

  -- Final Exam Q1
  ('vietnam-final-q1', 'vietnam-001', 'final_exam', NULL,
   'A PTM goes smoothly. The parent is warm, grateful, and asks no challenging questions. The teacher feels confident the relationship is strong. Which of the following should the teacher still consider?',
   $$[
     {"id":"vietnam-final-q1-a","text":"Nothing — a smooth meeting with a grateful parent is a good sign that the relationship is working.","isCorrect":false,"feedback":"In Vietnamese communication culture, a smooth meeting is a necessary but insufficient signal. Face-saving norms mean that concerns are processed privately, often after the meeting, through family discussion or parent networks.","explanation":"A smooth meeting in a face-saving culture tells you the relationship is polite. It does not tell you the parent is satisfied."},
     {"id":"vietnam-final-q1-b","text":"The parent may have concerns they chose not to raise because doing so would cost face for both parties. The teacher should follow up with a written summary and an explicit invitation to share concerns privately.","isCorrect":true,"feedback":"Yes. The face dynamic in Vietnamese PTMs means the real assessment often happens after the meeting. A written follow-up with specific next steps and an explicit invitation to raise concerns in writing gives the parent a lower-cost channel for the feedback they withheld in person.","explanation":"Providing a lower-cost channel for feedback after the meeting accounts for the face dynamic and invites the real conversation."},
     {"id":"vietnam-final-q1-c","text":"The teacher should ask a direct question at the end of the meeting: 'Is there anything you are concerned about that we have not discussed?'","isCorrect":false,"feedback":"Well-intentioned but culturally counterproductive. A direct question about concerns in a face-to-face meeting creates exactly the social pressure that face-saving norms are designed to avoid. The parent is likely to say 'no, everything is fine' regardless.","explanation":"Direct questions about concerns in a face-to-face context replicate the exact social pressure that face-saving norms are designed to manage."},
     {"id":"vietnam-final-q1-d","text":"The teacher should check with colleagues whether this parent has raised concerns through other channels.","isCorrect":false,"feedback":"Not wrong as a practice, but this is reactive rather than proactive. The better move is to create a communication structure that makes it easier for the parent to raise concerns before they travel through indirect channels.","explanation":"Checking with colleagues is reactive. Creating accessible feedback channels is proactive."}
   ]$$::jsonb,
   1),

  -- Final Exam Q2
  ('vietnam-final-q2', 'vietnam-001', 'final_exam', NULL,
   'A Vietnamese parent asks: "How does my child compare to the class average on this IB assignment?" What is the most research-aligned first response?',
   $$[
     {"id":"vietnam-final-q2-a","text":"Explain that IB does not rank students and redirect to the rubric criteria.","isCorrect":false,"feedback":"Technically accurate but practically unhelpful. The parent is asking for comparative data in the only format they know. Redirecting to the rubric without first addressing the underlying question — 'is my child competitive?' — leaves the question unanswered.","explanation":"Redirecting to the rubric answers a question the parent did not ask. The real question is about competitive positioning."},
     {"id":"vietnam-final-q2-b","text":"Provide a brief, honest assessment of the child's performance against the criteria, connect it to university outcomes ('students performing at this level are well-positioned for...'), and then explain what the rubric measures and how it connects to those outcomes.","isCorrect":true,"feedback":"Yes. This answers the competitive question first (using university outcomes as the legible frame), then explains the assessment system. The French academic tradition in urban Vietnam provides an additional bridge: framing portfolio work as rigorous structured argument rather than creative expression helps the assessment feel academically serious.","explanation":"Answer the competitive question first with outcome data, then explain the system. This respects the parent's actual information need."},
     {"id":"vietnam-final-q2-c","text":"Share the class average to build trust, then explain the limitations of averages.","isCorrect":false,"feedback":"Sharing class averages may seem practical but creates an expectation of ongoing comparative data that the school cannot sustain without rebuilding ranking culture. The better approach is to answer the competitive question through university outcomes rather than peer comparison.","explanation":"Sharing class averages sets an unsustainable precedent. University outcomes data addresses the same need without creating a ranking expectation."},
     {"id":"vietnam-final-q2-d","text":"Ask the parent why they want to compare — understanding their motivation will help you respond better.","isCorrect":false,"feedback":"This reverses the power dynamic inappropriately. The parent's motivation is clear from the cultural context: they need comparative data to assess whether the investment is working. Asking them to justify the question can feel interrogative.","explanation":"The parent's motivation is culturally legible. Asking them to justify it can feel like the teacher is questioning their right to the information."}
   ]$$::jsonb,
   2),

  -- Final Exam Q3
  ('vietnam-final-q3', 'vietnam-001', 'final_exam', NULL,
   'A student shows signs of high stress — difficulty sleeping, perfectionism about assignments, reluctance to submit work that is not flawless — alongside consistently high academic performance. A colleague says: "She is just a perfectionist — high achievers are like that." What is the most useful frame for understanding this pattern?',
   $$[
     {"id":"vietnam-final-q3-a","text":"The colleague is probably right — some students are naturally perfectionistic and it usually resolves with maturity.","isCorrect":false,"feedback":"This normalises a pattern that the research identifies as a risk indicator. In the Vietnamese context, perfectionism combined with high stress and high performance is consistent with authoritarian filial piety — obligation-driven study that is negatively associated with actual achievement and positively associated with depressive symptoms.","explanation":"Normalising this pattern misses a documented risk indicator. The research connects it to obligation-driven study and depression."},
     {"id":"vietnam-final-q3-b","text":"The student may be operating under authoritarian filial piety — studying out of obligation to repay parental sacrifice rather than intrinsic motivation. This pattern is documented as a risk factor for depression in Vietnamese students, and the high performance is masking, not resolving, the underlying stress.","isCorrect":true,"feedback":"Yes. The 2020 Frontiers study found that authoritarian filial piety is negatively associated with academic achievement and positively associated with depressive symptoms. The 27% depression rate in Hanoi secondary students provides background context. This student needs proactive pastoral attention, not reassurance that perfectionism is normal.","explanation":"Authoritarian filial piety combined with high stress is a documented depression risk factor. The high performance masks rather than resolves the problem."},
     {"id":"vietnam-final-q3-c","text":"The student needs better time management skills and study-life balance support.","isCorrect":false,"feedback":"Study skills are not the issue. The student is performing well academically. The stress is coming from the motivational structure — obligation, family honour, fear of disappointing — not from poor organisation. Addressing study skills treats the symptom while missing the cause.","explanation":"The student's time management is clearly functional given high performance. The stress source is motivational and cultural, not organisational."},
     {"id":"vietnam-final-q3-d","text":"The teacher should contact the parents to discuss reducing academic pressure at home.","isCorrect":false,"feedback":"Risky without careful framing. Telling Vietnamese parents that they are creating too much pressure can be heard as the school criticising the family's values. The better approach is to work with the family — framing the concern as 'we want to support your child's long-term success, including wellbeing' rather than 'you are causing the problem.'","explanation":"Framing the conversation as parental criticism risks the relationship. Working within the family honour frame is more effective."}
   ]$$::jsonb,
   3)

ON CONFLICT (id) DO UPDATE SET
  prompt  = EXCLUDED.prompt,
  options = EXCLUDED.options;


COMMIT;
