export const chinaCulturalVocab = {
  id: 'china-cultural-001',
  country: 'China',
  title: 'China: Five Cultural Terms',
  subtitle: 'Chinese concepts that shape how families think about reputation, relationship, and the purpose of education.',
  estimatedMinutes: 10,
  difficulty: 'foundational',
  type: 'cultural_vocab',
  facilitatorNote: "These terms come from inside Chinese social and educational culture. They are not stereotypes \u2014 they are lenses. Each one describes a real mechanism that operates in parent-teacher interactions, often invisibly to educators who have not encountered them before.",
  cards: [
    {
      id: 'mianzi',
      term: 'Mianzi',
      script: '\u9762\u5b50',
      pronunciation: 'MYEN-dzuh',
      literalTranslation: 'face / social reputation',
      learnerFriendlyDefinition: "Social reputation as a publicly held resource \u2014 something that can be given, maintained, or lost in the presence of others. Unlike internal shame, mianzi is about external standing in the eyes of the community.",
      whyItMatters: "Criticism delivered in a group setting, feedback that implies incompetence, or a student being visibly corrected in front of peers all carry mianzi costs. Parents may resist accurate feedback not because they disbelieve it, but because acknowledging it in the wrong setting damages their child\u2019s standing.",
      schoolExample: "A teacher praises six students publicly and gives one child quieter feedback afterward. The parent of that child thanks the teacher at the next PTM. The teacher handled mianzi correctly \u2014 the praise was public, the correction was private.",
      watchFor: "Strong reactions to public criticism. Parents who request private meetings before issues escalate. Students who shut down entirely after a visible failure rather than trying again.",
      contexts: ['parents', 'feedback', 'classroom'],
    },
    {
      id: 'guanxi',
      term: 'Guanxi',
      script: '\u5173\u7cfb',
      pronunciation: 'GWAHN-shee',
      literalTranslation: 'relational network / reciprocal obligation',
      learnerFriendlyDefinition: "A web of mutual obligations built through relationship maintenance over time. Guanxi is not simply networking \u2014 it is a moral economy of reciprocal investment where what you give creates what you can later expect.",
      whyItMatters: "A parent who has attended every school event, brought gifts on teacher appreciation day, or maintained warm regular contact is building guanxi \u2014 an informal account they expect to draw on when needed. Requests that feel presumptuous to a teacher may feel, to the parent, like a fair activation of a relational balance.",
      schoolExample: "A mother asks to have her son moved to the top maths group mid-term. The request seems pushy. She has volunteered for three school events this year. In her frame, she is making a reasonable relational request, not an unreasonable academic one.",
      watchFor: "Disproportionate generosity early in the year. Warm relationship investment that precedes a specific ask. Requests framed as coming from a friend or someone who knows the school.",
      contexts: ['parents', 'relationships', 'communication'],
    },
    {
      id: 'jiaoyu',
      term: 'Jiaoyu',
      script: '\u6559\u80b2',
      pronunciation: 'JYOW-yoo',
      literalTranslation: 'education / moral cultivation',
      learnerFriendlyDefinition: "Education understood as holistic moral cultivation \u2014 not simply academic instruction but the formation of character, conduct, and personhood. When parents ask about jiaoyu, they are asking whether the child is becoming a good person, not only a successful student.",
      whyItMatters: "Social development, respect for elders, behavioural discipline, and moral consistency are all part of jiaoyu. A report that focuses only on grades and misses character and conduct may feel incomplete or even dismissive to parents operating within this frame.",
      schoolExample: "A teacher reports that a student is performing well academically but struggles to cooperate in group tasks. The parents respond with deeper concern than the teacher expected. For them, the social failure is a jiaoyu failure \u2014 arguably more serious than an academic one.",
      watchFor: "Parental concern that extends beyond grades to character, conduct, or social behaviour. Questions about what the school is teaching children to be, not only what it is teaching them to do.",
      contexts: ['parents', 'behaviour', 'reporting'],
    },
    {
      id: 'suzhi',
      term: 'S\u00f9zh\u00ec',
      script: '\u7d20\u8d28',
      pronunciation: 'SOO-juh',
      literalTranslation: 'quality / inner cultivation',
      learnerFriendlyDefinition: "Innate quality or cultivated refinement \u2014 the aspiration toward educated, articulate, culturally capable personhood. Suzhi is what education is ultimately for: not grades, but the development of a capable, confident, well-rounded human being.",
      whyItMatters: "Families investing in English, music, public speaking, sport, and extra-curricular breadth are not simply keeping children busy \u2014 they are cultivating suzhi. Understanding this reframes what looks like pressure into a coherent aspiration toward human development.",
      schoolExample: "A family enrols their daughter in English tutoring, piano, and swimming on top of school. The teacher worries about overload. The parents see a developing person becoming more capable across all the domains that matter for a complete life.",
      watchFor: "Dense extra-curricular investment. Questions about confidence, articulacy, and character alongside academic performance. Parents who want the whole child developed, not just test scores improved.",
      contexts: ['parents', 'aspiration', 'extra-curricular'],
    },
    {
      id: 'keqi',
      term: 'K\u00e8q\u00ec',
      script: '\u5ba2\u6c14',
      pronunciation: 'kuh-CHEE',
      literalTranslation: 'polite restraint / not imposing',
      learnerFriendlyDefinition: "The social virtue of not placing burdens on others, expressed through indirect communication, declining before accepting, or softening requests to the point of near-invisibility. The indirect form is the culturally appropriate form.",
      whyItMatters: "A parent who says 'please don\u2019t trouble yourself' while clearly expecting a response is being k\u00e8q\u00ec. Reading this as disinterest or acceptance is a common misread. Repeated soft mentions of the same concern are not passive \u2014 they are a serious request in the only form that felt polite.",
      schoolExample: "A father emails to say: 'I know you are very busy and this is probably not important, but I was wondering if perhaps...' The teacher marks it low priority. The father has been making a serious request in the only form that felt appropriate to him.",
      watchFor: "Requests that arrive heavily hedged. Repeated soft mentions of the same concern across separate conversations. Emails that seem to minimise their own importance.",
      contexts: ['parents', 'communication', 'email'],
    },
  ],
}
