export const indiaCulturalVocab = {
  id: 'india-cultural-001',
  country: 'India',
  title: 'India: Five Cultural Terms',
  subtitle: 'Hindi and South Asian concepts that shape how families navigate honour, institutions, authority, and relationships.',
  estimatedMinutes: 15,
  difficulty: 'foundational',
  type: 'cultural_vocab',
  openingHook: {
    situation: [
      "You've emailed Arjun's parents three times in six weeks about the reading support plan you'd like to put in place. Polite emails, specific questions, clear next steps. Nothing. You begin to wonder if this family is simply disengaged.",
      "On a Thursday afternoon, five minutes before dismissal, a man you don't recognise appears at your classroom door. He smiles warmly, introduces himself as Arjun's father, and asks if you have a moment. He's completely relaxed, as if dropping by unannounced is entirely normal.",
      "You talk for fifteen minutes. He asks good questions. He clearly cares deeply about his son. He listens carefully to everything you say and responds thoughtfully.",
      "At the end he says, 'Yes, let's sort this out,' shakes your hand, and leaves. You stand in your empty classroom. You're not sure if you agreed on anything specific. You're also not sure why three careful emails produced nothing and an unannounced appearance produced the most engaged conversation you've had with any parent this term.",
    ],
    question: "Why didn't the emails work? And what made the doorway conversation real in a way they weren't?",
  },
  contextModifiers: {
    prompt: "Where are your Indian students from or living?",
    helpText: "India is enormously diverse, and these concepts reflect broad patterns in urban, aspirational, private-school contexts. Where your families are from \u2014 and where they are now \u2014 shapes which parts of the module land most directly.",
    options: [
      {
        id: 'in-india',
        label: 'Teaching in India',
        description: 'You are working at a school inside India',
        content: [
          "This module was written for your context. Izzat, jugaad, guru, rishta, and chalega all apply as described. One layer worth holding: regional diversity is enormous and genuinely matters. A Tamil family from Chennai, a Punjabi family from Chandigarh, and a Bengali family from Kolkata will each have distinct cultural expressions, communication styles, and relationship to authority \u2014 even while sharing the broad Hindi concepts in this module. The module gives you a starting framework; individual families will teach you their specific version.",
          "Caste sits in the background of almost every elite private school in India, rarely discussed openly but often structuring social networks, parent expectations, and community dynamics in ways that are not immediately visible. Families who are of different caste backgrounds may have subtly different relationships to the guru concept, to institutional authority, and to each other within the parent community. This is worth being aware of even if it is rarely foregrounded.",
          "The economic aspiration driving many Indian private school families is intense and explicitly intergenerational. Education is understood as the primary vehicle for family advancement, and parents are making significant financial sacrifices for school fees. This gives the guru relationship a specific urgency \u2014 the teacher is not just an educator but someone entrusted with the family's social trajectory.",
        ],
      },
      {
        id: 'gulf-diaspora',
        label: 'Indian families in the Gulf',
        description: 'UAE, Saudi Arabia, Qatar, Kuwait, Bahrain, Oman',
        content: [
          "The Indian diaspora in the Gulf is one of the largest in the world \u2014 approximately eight to nine million people \u2014 and it is not a uniform population. In international school contexts, you are typically dealing with the professional and aspirational tier: engineers, doctors, accountants, IT professionals, and business owners. But unlike the urban Indian professional in Delhi or Mumbai, many Gulf-based Indian families originally come from smaller cities and towns, often from Kerala, Andhra Pradesh, Tamil Nadu, or UP. Their cultural values tend to be more traditional than Indian metropolitan norms.",
          "Izzat is particularly heightened in the Gulf Indian community. These families are acutely aware that their child's school performance is visible not just locally but back home in India \u2014 through family WhatsApp groups, community networks, and the status signals that school names carry. Education is also a direct economic statement: the family is in the Gulf to build something, and the school is part of that investment story.",
          "Many Gulf-based Indian families intend to return to India eventually, or to move to a Western country. The international school is often understood as a stepping stone on one of these two trajectories. This shapes how parents engage with the curriculum \u2014 they are evaluating whether it positions their child well for Indian competitive entrance exams, for British A-levels, or for US college admissions, depending on the family's direction of travel.",
          "Jugaad is active here. Gulf-based Indian families are often excellent navigators of imperfect institutional systems \u2014 they have had to be. Informal channels, community connections, and direct approaches will be used alongside formal ones. Rishta within the Indian community is a significant resource: who you know within the Indian professional network shapes what you can access.",
        ],
      },
      {
        id: 'western-diaspora',
        label: 'Indian diaspora in the West',
        description: 'UK, US, Canada, Australia, New Zealand',
        content: [
          "British Indian, Indian-American, and Indian-Canadian communities are among the most educationally high-achieving diaspora populations in the world. The academic pressure this produces is often invisible to teachers because it operates primarily at home. A student who appears relaxed and socially confident at school may be managing intense family expectations tied to medicine, law, engineering, or finance as the only legitimate career paths. The concept of gongbu in the Korean module has a direct Indian-diaspora equivalent.",
          "The guru dynamic operates with particular force in these communities. Many Indian-diaspora parents are highly educated professionals \u2014 doctors, engineers, academics \u2014 who deeply respect educational authority and bring high expectations of that authority simultaneously. They may appear very comfortable navigating Western institutional culture while privately evaluating the teacher against demanding standards. Criticism delivered without sufficient authority or expertise will land poorly.",
          "Generational tension is significant. Second-generation students have often fully internalized Western individualism \u2014 they expect voice, self-determination, and the right to deviate from family plans. Their parents hold Indian collective expectations: family priority, community standing, academic seriousness. The student navigating these two systems simultaneously may appear inconsistent or ambivalent; this is usually the pull between two legitimate but incompatible frameworks.",
          "Community infrastructure is dense in cities like London, Toronto, and parts of the US. Indian cultural associations, temple communities, and weekend language schools maintain cultural continuity. Rishta within this network is a real social resource. A parent who is well-connected in the Indian community may bring those connections to bear on school interactions in ways that are not always obvious to a teacher without a window into that world.",
        ],
      },
      {
        id: 'southeast-asia',
        label: 'Indian diaspora in Southeast Asia',
        description: 'Singapore, Malaysia, and beyond',
        content: [
          "Tamil communities in Singapore and Malaysia have been established for over a century, with roots in South Indian labour migration under British colonial administration. These families are distinct from recent Indian professional arrivals and from the broader Indian diaspora in the West. A Tamil Singaporean family has a Singaporean identity, a Singaporean educational history, and a specific relationship to Tamil language and Hindu practice that does not map neatly onto a mainland Indian frame.",
          "Singapore's highly competitive educational system has shaped Indian-Singaporean families significantly. Many are accustomed to rigorous academic benchmarking and may bring precise expectations to an international school \u2014 expectations that are as much Singaporean as they are Indian. The guru concept is present, but filtered through Singapore's meritocratic institutional culture, which gives it a more transactional quality than you might find in India itself.",
          "Indian communities in Malaysia have a more complex position \u2014 historically marginalised under Malaysian affirmative action policies that favour the Malay majority, Indian-Malaysian families often have an acute awareness of their minority status and its implications for their children's futures. Education is understood as the primary tool available to them, which intensifies academic investment and the izzat carried by school performance.",
          "Across Southeast Asia, recent Indian professional arrivals \u2014 IT workers, consultants, corporate professionals \u2014 form a distinct population from established community families. They are often in the country temporarily, highly internationally mobile, and may have already lived in multiple countries. Their cultural values are recognisably Indian but their institutional fluency is high. They tend to be direct, expectations-clear parents who are comfortable navigating international school systems.",
        ],
      },
    ],
  },
  facilitatorNote: "India is vastly diverse, and no five terms can represent every family or region. These concepts are widely shared enough across urban, aspirational, private-school contexts to be genuinely useful \u2014 but always hold them loosely and let individual families teach you their own version.",
  cards: [
    {
      id: 'izzat',
      term: 'Izzat',
      script: '\u0907\u091c\u093c\u094d\u091c\u0924',
      pronunciation: 'IZ-zaht',
      literalTranslation: 'family honour / respect',
      learnerFriendlyDefinition: "Social standing earned and maintained through community-visible behaviour: educational investment, proper conduct, visible seriousness, and public aspiration. Izzat is accumulated across generations and can be damaged by public failure.",
      whyItMatters: "A parent's visible commitment to their child's schooling \u2014 attending every meeting, buying the right uniform, hiring tutors \u2014 is partly izzat maintenance: evidence to the neighbourhood and extended family that this family takes its children's future seriously. Criticism of a child, delivered carelessly, can be received as an izzat threat.",
      schoolExample: "A teacher sends a note home about missed homework in an open envelope that the child's grandmother sees first. The family does not respond for a week. The grandmother's witnessing of the note introduced an izzat dimension the teacher had not anticipated.",
      watchFor: "Visible parental investment that goes well beyond school expectation. Sensitivity to how information is communicated, especially anything that could be seen by people outside the immediate family.",
      contexts: ['parents', 'feedback', 'communication'],
      cardScenario: {
        situation: "You need to inform a family that their child failed a key assessment. You call the home number during the school day.",
        withUnderstanding: "You call at an agreed time, confirm both parents are available, and open with the child's strengths before the concern. You frame the assessment result as a specific point to address together, not a reflection of the child's character. The conversation is private, warm, and specific.",
        withoutUnderstanding: "You call the home number and the grandmother answers. She hears enough to understand the child has failed something. The parents call back that evening, embarrassed and defensive. The concern you wanted to address collaboratively has become an izzat incident.",
      },
    },
    {
      id: 'jugaad',
      term: 'Jugaad',
      script: '\u091c\u0941\u0917\u093e\u0921\u093c',
      pronunciation: 'joo-GAARD',
      literalTranslation: 'creative workaround / improvisation',
      learnerFriendlyDefinition: "Resourceful, creative improvisation in the face of imperfect or unresponsive systems \u2014 a survival skill refined through long experience with bureaucratic institutions that do not always serve people well.",
      whyItMatters: "A family using jugaad is not being dishonest or rule-breaking. They are applying adaptive intelligence. Approaching a senior teacher directly, bringing a bilingual relative to a meeting, or finding an informal route to a resource are all jugaad. Reading this as circumventing proper process misses the ingenuity it takes to navigate systems that were not built for you.",
      schoolExample: "A father cannot get a response to his emails about his daughter's learning support plan. He arrives at the school gate at pickup and speaks to the coordinator directly. The school sees this as bypassing channels. The father sees it as problem-solving.",
      watchFor: "Non-standard approaches to school processes. Requests that arrive through unexpected channels. Parents who seem to work around systems rather than through them.",
      contexts: ['parents', 'communication', 'access'],
      cardScenario: {
        situation: "A parent has sent three emails about their son's learning support provision without a reply. They now arrive unannounced at the school office asking to speak with you.",
        withUnderstanding: "You give them five minutes now and schedule a proper meeting for the following day. You understand the unannounced arrival as jugaad \u2014 they found the most direct path available after the formal channel failed. You also note that your response time needs improving.",
        withoutUnderstanding: "You ask the receptionist to tell them appointments are required and to email the year group admin. They try again informally twice more. Eventually they contact the school governor. What was a simple communication gap has escalated significantly.",
      },
    },
    {
      id: 'guru',
      term: 'Guru',
      script: '\u0917\u0941\u0930\u0941',
      pronunciation: 'GOO-roo',
      literalTranslation: 'revered teacher / moral guide',
      learnerFriendlyDefinition: "In Indian tradition, the teacher is a moral authority, spiritual guide, and custodian of knowledge \u2014 deserving deep deference, not merely professional respect. The guru-shishya (teacher-student) relationship carries a weight that transcends the classroom.",
      whyItMatters: "Families operating within a guru framework approach teachers with formal deference, express disagreement indirectly, and may assume the teacher's judgment is final. Teachers who invite challenge, adopt informal styles, or minimise their own authority can confuse families who interpret this as a lack of seriousness or competence.",
      schoolExample: "A teacher opens a PTM by saying: 'I want this to be a two-way conversation \u2014 please push back if you disagree.' The parent nods but does not speak freely. In their frame, openly challenging a guru is improper, regardless of the invitation.",
      watchFor: "Excessive deference that makes honest feedback difficult to gather. Students who agree publicly and then do not follow through \u2014 they may be managing the guru relationship rather than making genuine commitments.",
      contexts: ['parents', 'students', 'authority'],
      cardScenario: {
        situation: "You use a casual, first-name-basis style with your class and regularly invite students to challenge your ideas during discussions. Two students from one family are consistently reluctant to engage in debate, even when you explicitly invite it.",
        withUnderstanding: "You understand that your informality may be reading as incompetence or unseriousness through a guru lens. You explain your pedagogical approach explicitly to the family at PTM and create a clear structure for respectful disagreement. The students begin to engage with guidance.",
        withoutUnderstanding: "You continue as normal and note in their files that they lack critical thinking confidence. The parents request a meeting and ask whether you are fully qualified \u2014 they associate informality with inexperience. You are surprised by the question.",
      },
    },
    {
      id: 'rishta',
      term: 'Rishta',
      script: '\u0930\u093f\u0936\u094d\u0924\u093e',
      pronunciation: 'RISH-tah',
      literalTranslation: 'relationship / social connection',
      learnerFriendlyDefinition: "A network of relationships \u2014 family, community, school \u2014 that carry mutual obligation and shape access, trust, and cooperation. Rishta is the social infrastructure through which many important things happen.",
      whyItMatters: "A teacher who has built genuine rishta with a family gets more latitude when delivering difficult news. A family with existing connections inside the school may navigate very differently from one without them. Relationship investment at the start of the year pays dividends during difficult conversations later.",
      schoolExample: "A new teacher struggles to get a difficult family to engage. A senior colleague who has known the family for years joins one meeting. The dynamic shifts immediately. The colleague has rishta; the new teacher does not yet.",
      watchFor: "Conversations that go smoothly when a known intermediary is present. Families who respond differently to different staff. Early relationship investment that seems disproportionate to the moment.",
      contexts: ['relationships', 'parents', 'communication'],
      cardScenario: {
        situation: "You need to share difficult news about a student's learning support assessment with a family you have only met twice.",
        withUnderstanding: "You ask a colleague who knows the family well to join the meeting. You invest the first ten minutes in warmth and genuine connection before moving to the concern. The rishta of your colleague bridges the gap in your own. The family engages with the support plan.",
        withoutUnderstanding: "You deliver the news at the scheduled PTM slot, efficiently and kindly. The parents are polite but guarded. They say they need to think about it. Follow-through is minimal. At the next meeting you raise the same concern.",
      },
    },
    {
      id: 'chalega',
      term: 'Chalega',
      script: '\u091a\u0932\u0947\u0917\u093e',
      pronunciation: 'chah-LEH-gah',
      literalTranslation: "it'll do / it'll work out",
      learnerFriendlyDefinition: "A cultural orientation toward flexibility, approximate compliance, and tolerating imperfection. Not laziness, but a pragmatic acceptance that things do not need to be precisely right to be workable.",
      whyItMatters: "A parent who agrees to a plan and implements something approximately similar is not disrespecting the agreement \u2014 they may be applying a deeply held flexibility around precision. Teachers who expect exact compliance may be misreading a cultural orientation as unreliability.",
      schoolExample: "A reading plan asks a family to read for 15 minutes each evening and return a log on Fridays. The family reads most evenings, sometimes for 10 minutes, and brings the log roughly every other week. The teacher marks this as non-compliance. The family feels they have been cooperative.",
      watchFor: "Agreements honoured in spirit but not detail. Follow-through that is present but inexact. Plans that need check-ins built in rather than precise compliance assumed.",
      contexts: ['parents', 'homework', 'follow-through'],
      cardScenario: {
        situation: "A family agreed at PTM to a structured nightly reading plan with a weekly log returned every Friday. After four weeks, the log comes back every other week and is sometimes incomplete.",
        withUnderstanding: "You check in warmly at pickup: 'The reading is clearly happening \u2014 I can see it in her fluency. Want to simplify the log so it's easier to keep track?' The parent is relieved. Engagement with the simplified version is consistent.",
        withoutUnderstanding: "You send a formal note home about the incomplete log. The parent feels unfairly criticised after trying their best. They stop returning the log entirely and become less responsive at the next PTM.",
      },
    },
  ],
  reviewScenarios: [
    {
      id: 'india-review-1',
      title: 'The Learning Support Conversation',
      termsInPlay: ['izzat', 'guru', 'rishta'],
      situation: "You need to share that a student requires a formal learning support assessment. The family is well-regarded in the school community and has a reputation for taking education very seriously. You know them only from two brief PTM conversations.",
      withUnderstanding: "You invite both parents at a time they can both attend, ask a trusted colleague who knows the family to join, and open the meeting with the student's genuine strengths. You frame the assessment through the guru lens: this is knowledge you're sharing to help their child flourish, not a judgement. Izzat is protected throughout \u2014 the meeting is private, warm, and collaborative. Rishta is built by the colleague's presence and your care. The family agrees to the assessment.",
      withoutUnderstanding: "You deliver the news at a routine PTM slot. The father is surprised and says he needs to 'think about it.' He hasn't been prepared, the rishta isn't there to absorb the shock, and in his frame the teacher has delivered a verdict rather than shared knowledge. The assessment is delayed for months.",
    },
    {
      id: 'india-review-2',
      title: 'The Informal Channel',
      termsInPlay: ['jugaad', 'chalega', 'rishta'],
      situation: "A parent who has never responded to your formal emails arrives at the school gate on two separate occasions this week, asking for informal updates on their child's maths progress. They are friendly and clearly engaged with their child's education, just not through the channels the school has set up.",
      withUnderstanding: "You recognise the jugaad approach and understand the rishta gap: the formal system doesn't feel accessible to this family yet. You establish a brief weekly verbal check-in at pickup and accept that chalega-level follow-through is what they can offer for now. You adapt to their channel rather than insisting on yours. Over the term, engagement and trust build.",
      withoutUnderstanding: "You redirect them to the parent portal twice and note in the file that the family is disengaged. The child loses access to the informal advocacy the parent was trying to provide. The parent eventually stops coming to pickup. At end of year, you note this family as 'difficult to reach.'",
    },
  ],
}
