export const indiaCulturalVocab = {
  id: 'india-cultural-001',
  country: 'India',
  title: 'India: Five Cultural Terms',
  subtitle: 'Hindi and South Asian concepts that shape how families navigate honour, institutions, authority, and relationships.',
  estimatedMinutes: 10,
  difficulty: 'foundational',
  type: 'cultural_vocab',
  facilitatorNote: "India is vastly diverse, and no five terms can represent every family or region. These concepts are widely shared enough across urban, aspirational, private-school contexts to be genuinely useful \u2014 but always hold them loosely and let individual families teach you their own version.",
  cards: [
    {
      id: 'izzat',
      term: 'Izzat',
      script: '\u0907\u091c\u093c\u094d\u091c\u0924',
      pronunciation: 'IZ-zaht',
      literalTranslation: 'family honour / respect',
      learnerFriendlyDefinition: "Social standing earned and maintained through community-visible behaviour: educational investment, proper conduct, visible seriousness, and public aspiration. Izzat is accumulated across generations and can be damaged by public failure.",
      whyItMatters: "A parent\u2019s visible commitment to their child\u2019s schooling \u2014 attending every meeting, buying the right uniform, hiring tutors \u2014 is partly izzat maintenance: evidence to the neighbourhood and extended family that this family takes its children\u2019s future seriously. Criticism of a child, delivered carelessly, can be received as an izzat threat.",
      schoolExample: "A teacher sends a note home about missed homework in an open envelope that the child\u2019s grandmother sees first. The family does not respond for a week. The grandmother\u2019s witnessing of the note introduced an izzat dimension the teacher had not anticipated.",
      watchFor: "Visible parental investment that goes well beyond school expectation. Sensitivity to how information is communicated, especially anything that could be seen by people outside the immediate family.",
      contexts: ['parents', 'feedback', 'communication'],
    },
    {
      id: 'jugaad',
      term: 'Jugaad',
      script: '\u091c\u0941\u0917\u093e\u0921\u093c',
      pronunciation: 'joo-GAARD',
      literalTranslation: 'creative workaround / improvisation',
      learnerFriendlyDefinition: "Resourceful, creative improvisation in the face of imperfect or unresponsive systems \u2014 a survival skill refined through long experience with bureaucratic institutions that do not always serve people well.",
      whyItMatters: "A family using jugaad is not being dishonest or rule-breaking. They are applying adaptive intelligence. Approaching a senior teacher directly, bringing a bilingual relative to a meeting, or finding an informal route to a resource are all jugaad. Reading this as circumventing proper process misses the ingenuity it takes to navigate systems that were not built for you.",
      schoolExample: "A father cannot get a response to his emails about his daughter\u2019s learning support plan. He arrives at the school gate at pickup and speaks to the coordinator directly. The school sees this as bypassing channels. The father sees it as problem-solving.",
      watchFor: "Non-standard approaches to school processes. Requests that arrive through unexpected channels. Parents who seem to work around systems rather than through them.",
      contexts: ['parents', 'communication', 'access'],
    },
    {
      id: 'guru',
      term: 'Guru',
      script: '\u0917\u0941\u0930\u0941',
      pronunciation: 'GOO-roo',
      literalTranslation: 'revered teacher / moral guide',
      learnerFriendlyDefinition: "In Indian tradition, the teacher is a moral authority, spiritual guide, and custodian of knowledge \u2014 deserving deep deference, not merely professional respect. The guru-shishya (teacher-student) relationship carries a weight that transcends the classroom.",
      whyItMatters: "Families operating within a guru framework approach teachers with formal deference, express disagreement indirectly, and may assume the teacher\u2019s judgment is final. Teachers who invite challenge, adopt informal styles, or minimise their own authority can confuse families who interpret this as a lack of seriousness or competence.",
      schoolExample: "A teacher opens a PTM by saying: 'I want this to be a two-way conversation \u2014 please push back if you disagree.' The parent nods but does not speak freely. In their frame, openly challenging a guru is improper, regardless of the invitation.",
      watchFor: "Excessive deference that makes honest feedback difficult to gather. Students who agree publicly and then do not follow through \u2014 they may be managing the guru relationship rather than making genuine commitments.",
      contexts: ['parents', 'students', 'authority'],
    },
    {
      id: 'rishta',
      term: 'Rishta',
      script: '\u0930\u093f\u0936\u094d\u0924\u093e',
      pronunciation: 'RISH-tah',
      literalTranslation: 'relationship / social connection',
      learnerFriendlyDefinition: "A network of relationships \u2014 family, community, school \u2014 that carry mutual obligation and shape access, trust, and cooperation. Rishta is the social infrastructure through which many important things happen.",
      whyItMatters: "A teacher who has built genuine rishta with a family gets more latitude when delivering difficult news. A family with existing connections inside the school may navigate very differently from one without them. Relationship investment at the start of the year pays dividends during difficult conversations later.",
      schoolExample: "A new teacher struggles to get a difficult family to engage. A senior colleague who has known the family for years joins one meeting. The dynamic shifts immediately. The colleague has rishta; the new teacher does not yet.",
      watchFor: "Conversations that go smoothly when a known intermediary is present. Families who respond differently to different staff. Early relationship investment that seems disproportionate to the moment.",
      contexts: ['relationships', 'parents', 'communication'],
    },
    {
      id: 'chalega',
      term: 'Chalega',
      script: '\u091a\u0932\u0947\u0917\u093e',
      pronunciation: 'chah-LEH-gah',
      literalTranslation: "it'll do / it'll work out",
      learnerFriendlyDefinition: "A cultural orientation toward flexibility, approximate compliance, and tolerating imperfection. Not laziness, but a pragmatic acceptance that things do not need to be precisely right to be workable.",
      whyItMatters: "A parent who agrees to a plan and implements something approximately similar is not disrespecting the agreement \u2014 they may be applying a deeply held flexibility around precision. Teachers who expect exact compliance may be misreading a cultural orientation as unreliability.",
      schoolExample: "A reading plan asks a family to read for 15 minutes each evening and return a log on Fridays. The family reads most evenings, sometimes for 10 minutes, and brings the log roughly every other week. The teacher marks this as non-compliance. The family feels they have been cooperative.",
      watchFor: "Agreements honoured in spirit but not detail. Follow-through that is present but inexact. Plans that need check-ins built in rather than precise compliance assumed.",
      contexts: ['parents', 'homework', 'follow-through'],
    },
  ],
}
