export const koreaCulturalVocab = {
  id: 'korea-cultural-001',
  country: 'South Korea',
  title: 'Korea: Five Cultural Terms',
  subtitle: 'Korean concepts that shape how students read rooms, how families protect dignity, and how relationships hold weight.',
  estimatedMinutes: 15,
  difficulty: 'foundational',
  type: 'cultural_vocab',
  openingHook: {
    situation: [
      "It's a Tuesday afternoon. Your Year 8 class is in the middle of what has genuinely been a very good lesson. The discussion is alive. Then you introduce the next task \u2014 a challenge question, the kind that requires real thinking. You ask them to share their initial thoughts.",
      "Silence. Not the blank silence of confusion. Something different. Twenty-three students look at you with complete, still attention. No one reaches for a pen. No one whispers to a neighbour. One student \u2014 your most confident \u2014 glances very briefly to her left and right before raising her hand. She gives a careful answer, not a bold one.",
      "You move on, but something stays with you. What were they waiting for? What was the glance about? You asked the same question at your school in London last year and four hands went up immediately.",
      "A Korean colleague passes you in the corridor after school. You describe what happened. She nods immediately: 'Yes. They were being careful.' You wait for more. That's all she says.",
    ],
    question: "What were the students waiting for before anyone answered? What did the glance mean?",
  },
  contextModifiers: {
    prompt: "Where are your Korean students living?",
    helpText: "Korean cultural values are consistent, but how they show up in school depends on the family's context. Select your setting to see what shifts.",
    options: [
      {
        id: 'southeast-asia',
        label: 'Southeast Asia',
        description: 'Vietnam, Indonesia, Thailand, Philippines',
        flag: '\uD83C\uDF0F',
        content: [
          "Korean families in Southeast Asia are often connected to Korean corporate investment in the region \u2014 manufacturing, retail, construction. This means many parents are professionals tied to Korean company hierarchies, which tends to reinforce traditional Korean values around authority and discipline rather than soften them.",
          "Korea's cultural soft power (K-pop, K-drama, Korean beauty) has made Korean students unusually high-status socially in Southeast Asian peer groups. Your Korean students may be aware of this in ways that shape their confidence and expectations \u2014 and that can occasionally produce a sense of exceptionalism that isn't present in other contexts.",
          "The host culture's alignment on hierarchy and collectivism means Korean families often find the broader social environment legible. However, this can make Western progressive pedagogy feel particularly jarring by contrast. Parents who are comfortable with the local culture's deference to authority may be especially skeptical of inquiry-based, student-led, or openly democratic classroom approaches \u2014 not because they are unfamiliar, but because they see Korean rigour as demonstrably superior.",
          "Hagwon-equivalent supplementary education is widely available and heavily used. Expect Korean students to be managing significant out-of-school academic load alongside your programme.",
        ],
      },
      {
        id: 'middle-east',
        label: 'Middle East',
        description: 'Saudi Arabia, UAE, Qatar, Kuwait',
        flag: '\uD83C\uDF05',
        content: [
          "Korean families in the Middle East are typically professionals in engineering, construction, healthcare, or energy \u2014 sectors where Korean companies have had a significant Gulf presence since the 1970s. These families tend to be more conservative and traditional than Korean urban professional families, and their educational expectations are correspondingly high.",
          "The Korean church is the social centre of Korean community life in the Gulf. Korean evangelical Christianity is a significant force, and it means the Korean community is tight, insular, and often mutually aware. A pastoral issue involving one Korean family may be known to others before you are aware of it yourself. This is not gossip \u2014 it is community care operating the way it does.",
          "There is partial value alignment between Korean and Arab-Islamic culture \u2014 both are collectivist, family-oriented, and hierarchical. But the divergence around religion is significant. Korean Christian families navigating a Muslim-majority context are managing a layer of identity guardedness that isn't visible in other settings. This can make some families appear more closed or formal than Korean families in East Asian or Western contexts.",
          "Academic expectations and chemyeon intensity are high. Within the Korean community, children's school performance is visible and carries social weight. A concern raised at school can feel like it has community implications beyond the immediate family.",
        ],
      },
      {
        id: 'north-america-australia',
        label: 'North America / Australia',
        description: 'US, Canada, Australia, New Zealand',
        flag: '\uD83C\uDF0E',
        content: [
          "Korean communities in North America and Australia are among the most established Korean diaspora populations in the world. In cities like Los Angeles, Toronto, and Sydney, Korean cultural infrastructure \u2014 church, supplementary school, social networks \u2014 is dense enough that families can maintain Korean cultural life largely within the Korean community. This means home values are often preserved more intact than you might expect.",
          "The most important dynamic to understand here is generational tension. Students who are second-generation or who arrived young have typically internalized significant Western individualism \u2014 they expect voice, agency, and the right to express preference. Their parents hold Korean collective expectations: deference, academic seriousness, family priority. The student you see at school and the student who goes home may be navigating genuinely different operating systems. What looks like inconsistency or ambivalence is often this.",
          "Hagwon culture is intense in Korean-North American communities \u2014 often more so than in Korea itself, because parents feel the cultural pressure of raising Korean children in an individualist environment. Expect significant out-of-school academic load and strong parental investment in measurable performance outcomes.",
          "Parents may appear very comfortable navigating Western institutional settings \u2014 they speak the language, they know the system. But this fluency can obscure traditional expectations that operate strongly at home. A parent who seems relaxed and Western in a PTM may be applying significant academic and cultural pressure at home that the student never mentions.",
        ],
      },
      {
        id: 'europe',
        label: 'Europe',
        description: 'UK, Germany, France, Netherlands, and beyond',
        flag: '\uD83C\uDDEA\uD83C\uDDFA',
        content: [
          "Korean communities in European cities are typically smaller and less infrastructurally self-sufficient than in North America or Southeast Asia. Without a large Korean church or a Korean school system nearby, families are more socially isolated, and the international school carries more weight as a community anchor than it does elsewhere.",
          "The cultural distance is significant. Northern European school cultures \u2014 flat hierarchies, egalitarian teacher-student relationships, emphasis on student self-direction and open disagreement \u2014 represent almost an inversion of Korean educational values. A Danish or Dutch classroom, to a Korean student, may feel structureless or even disrespectful. Parents may interpret a teacher's informality or openness to student challenge as a sign that the school lacks rigour.",
          "Students in European contexts often adapt to local peer culture relatively quickly, which can create visible parent-child tension around identity. The student may be becoming European in ways the parents did not anticipate and are not comfortable with. This can make parents appear more anxious or controlling than Korean parents in more culturally familiar environments.",
          "Because the Korean community is thin, teachers in European international schools are often working without any Korean cultural support around them. There may be no Korean-speaking colleague, no Korean community organisation to refer to, no institutional memory of how to read Korean parent behaviour. This makes the base cultural vocabulary \u2014 nunchi, chemyeon, kibun, jeong, gongbu \u2014 especially important: you may be the only person in the building who has stopped to think about any of this.",
        ],
      },
    ],
  },
  facilitatorNote: "The Korea module already uses the word hagwon. These five terms go deeper into the social and relational logic that sits beneath academic pressure \u2014 the invisible operating system that teachers often sense but struggle to name.",
  cards: [
    {
      id: 'nunchi',
      term: 'Nunchi',
      script: '\ub208\uce58',
      pronunciation: 'NOON-chee',
      literalTranslation: 'social reading ability / reading the room',
      learnerFriendlyDefinition: "The ability to accurately read unspoken social cues, emotional atmosphere, and others' unexpressed expectations \u2014 without being told. A core social competence that Koreans develop from childhood.",
      whyItMatters: "A student with strong nunchi adjusts their behaviour before a teacher intervenes. A teacher with strong nunchi is respected; one who misses obvious signals is seen as cold or unaware. A quiet, self-correcting classroom is not passivity \u2014 it is nunchi in action.",
      schoolExample: "A teacher's tone shifts slightly when a student's answer goes in the wrong direction. Every other student recalibrates. The student who gave the answer does not \u2014 and keeps elaborating. The class registers this as a nunchi failure.",
      watchFor: "Students who self-regulate before being asked. Group dynamics that shift in response to teacher mood without any words being exchanged. Peer pressure that enforces conformity silently.",
      contexts: ['students', 'classroom', 'social dynamics'],
      cardScenario: {
        situation: "You introduce a new activity that requires students to risk publicly wrong answers. The room goes unusually quiet and participation drops significantly.",
        withUnderstanding: "You recognise that the class is reading the social risk \u2014 their nunchi is telling them this setting is dangerous for mistakes. You model a wrong answer yourself, name it as normal, and start with pair-share before full-group. Participation gradually recovers.",
        withoutUnderstanding: "You interpret the silence as confusion and repeat the instructions more loudly and slowly. The discomfort deepens. One student attempts an answer, gets it wrong, and the others go even quieter. You end the lesson feeling frustrated.",
      },
    },
    {
      id: 'chemyeon',
      term: 'Chemyeon',
      script: '\uccb4\uba74',
      pronunciation: 'cheh-MYUN',
      literalTranslation: 'social face / dignity',
      learnerFriendlyDefinition: "Social face \u2014 the publicly maintained dignity that comes from fulfilling one's role appropriately, achieving socially visible success, and avoiding public embarrassment. Korea's version of face, distinct from the Chinese concept of mianzi.",
      whyItMatters: "Chemyeon is lost through public correction, academic failure in visible settings, or being associated with failure. A student who cannot recover their chemyeon after a public stumble may disengage entirely rather than risk further loss. Parents whose child is criticised at a meeting feel their own chemyeon is implicated.",
      schoolExample: "A teacher corrects a student's grammar in front of the class, expecting this to be a learning moment. The student goes quiet for the rest of the week. Their chemyeon was damaged and they have no strategy for recovering it in this setting.",
      watchFor: "Withdrawal after visible failure. Students who refuse to attempt tasks they might get wrong publicly. Parents who respond to feedback as if they personally have been criticised.",
      contexts: ['students', 'parents', 'feedback'],
      cardScenario: {
        situation: "A student fails a timed presentation in front of peers \u2014 they lose their place, go silent, and sit down before finishing. The class is uncomfortable. You move on quickly.",
        withUnderstanding: "You approach the student privately after class. You acknowledge how hard that felt, validate their capability, and create a lower-stakes re-entry: presenting to you first, then a small group, then the full class. Their chemyeon is recovered incrementally.",
        withoutUnderstanding: "The next day you encourage them publicly to 'just give it another go \u2014 everyone struggles sometimes.' They decline. They do not attempt a presentation again for the rest of the year.",
      },
    },
    {
      id: 'kibun',
      term: 'Kibun',
      script: '\uae30\ubd84',
      pronunciation: 'KEE-boon',
      literalTranslation: 'mood / emotional atmosphere',
      learnerFriendlyDefinition: "The prevailing emotional mood or atmosphere of an interaction \u2014 something that can be maintained, disrupted, or gradually restored. Good kibun keeps a conversation productive; disrupted kibun may end real communication even if the conversation continues on the surface.",
      whyItMatters: "Skilled navigators of Korean social settings read kibun continuously and adjust \u2014 pausing, softening, or redirecting when the atmosphere shifts. Teachers who monitor kibun can navigate parent-teacher conversations more effectively than those who push through regardless of emotional climate.",
      schoolExample: "A parent meeting is going well. The teacher introduces a concern about attendance too directly. The parent's kibun shifts \u2014 they become politely non-committal for the rest of the meeting. The teacher thinks the point landed. It did not.",
      watchFor: "Sudden polite vagueness after a direct comment. Nodding that does not translate into agreement or follow-through. The moment the energy in a meeting changes and the other person becomes formal.",
      contexts: ['parents', 'communication', 'meetings'],
      cardScenario: {
        situation: "A parent meeting begins well. You raise a concern about their child's lateness to school midway through. The parent's posture shifts slightly. They say 'I understand' and nod, but give no follow-up.",
        withUnderstanding: "You notice the kibun shift and pause. You soften: 'I know mornings can be difficult \u2014 I just want to make sure we're supporting her well.' The parent relaxes slightly and shares that there's been a family situation at home. A real conversation opens.",
        withoutUnderstanding: "You continue through the rest of the agenda efficiently. The parent agrees to everything, leaves politely, and nothing changes. At the next meeting you raise lateness again.",
      },
    },
    {
      id: 'jeong',
      term: 'Jeong',
      script: '\uc815',
      pronunciation: 'JUNG',
      literalTranslation: 'relational bond / attachment',
      learnerFriendlyDefinition: "A deep emotional connection formed through time and shared experience \u2014 not romantic, but warm, loyal, and hard to articulate. Jeong accumulates slowly and is felt as a genuine loss when severed.",
      whyItMatters: "Teachers who stay at a school for years build jeong with families. Students who have been genuinely supported through difficulty feel jeong toward those teachers. This explains why relationship consistency matters enormously in Korean school communities \u2014 and why transitions and teacher changes are felt as real losses, not just administrative inconveniences.",
      schoolExample: "A beloved Year 4 teacher leaves at the end of the year. Several families send extended farewell messages. One writes: 'our son has not stopped talking about this.' This is jeong \u2014 not sentiment, but a genuine relational bond being severed.",
      watchFor: "Disproportionate responses to teacher departures. Students who maintain unusual loyalty to particular teachers over years. The weight families give to long-term relational continuity with specific staff.",
      contexts: ['relationships', 'transitions', 'parents'],
      cardScenario: {
        situation: "A teacher who has been with the school for four years announces they are leaving at the end of term. Several students become distracted in the following weeks and one stops completing homework.",
        withUnderstanding: "You understand this as jeong \u2014 a real relational loss, not behavioural regression. You name the transition explicitly with the class, hold space for the feelings, and create a small closing ritual. The student's engagement gradually stabilises.",
        withoutUnderstanding: "You treat the homework gap as a discipline issue and increase pressure. The student withdraws further. Their parents request a meeting to discuss whether the school environment is still right for their child.",
      },
    },
    {
      id: 'gongbu',
      term: 'Gongbu',
      script: '\uacf5\ubd80',
      pronunciation: 'GONG-boo',
      literalTranslation: 'study / diligent learning',
      learnerFriendlyDefinition: "Study and learning understood as a cultural virtue and moral duty \u2014 not merely an academic activity. Gongbu is an identity, not a task. A student who does gongbu is becoming the right kind of person.",
      whyItMatters: "A student who is not studying diligently is not simply underperforming academically \u2014 they are failing a cultural obligation to their family and themselves. This explains the weight Korean families attach to academic concern, and why 'they're not working to their potential' can land as a character indictment, not a progress note.",
      schoolExample: "A teacher tells a parent that their son is bright but not putting in consistent effort. The parent's reaction is more intense than the teacher expected. In their frame, the issue is not academic performance \u2014 it is whether their child is becoming the kind of person who does gongbu.",
      watchFor: "Extreme parental investment in effort signals, not just attainment. Students who self-identify as hard workers even when outcomes are mixed. The emotional weight parents give to conversations about effort specifically.",
      contexts: ['parents', 'students', 'effort'],
      cardScenario: {
        situation: "A parent contacts you to say their child \u2014 who has an A average \u2014 is worried they are not working hard enough. The parent seems genuinely anxious.",
        withUnderstanding: "You understand this as a gongbu concern. It's about identity and virtue, not grades. You affirm the child's diligence specifically with concrete examples and offer visible effort-tracking so both the child and family can see the gongbu clearly. The anxiety settles.",
        withoutUnderstanding: "You reassure the parent that the grades are excellent and there is nothing to worry about. They thank you but remain unconvinced. The child continues to feel inadequate despite strong performance.",
      },
    },
  ],
  reviewScenarios: [
    {
      id: 'korea-review-1',
      title: 'The Silent Classroom',
      termsInPlay: ['nunchi', 'kibun', 'chemyeon'],
      situation: "You introduce a Socratic seminar format where students are expected to challenge each other's ideas directly. The class has been enthusiastic and talkative in small group work all term. In the seminar, the room is almost completely silent. One student makes a tentative comment and is gently disagreed with by another. They go red and do not speak again.",
      withUnderstanding: "You recognise three things happening at once: the class's nunchi is telling them this format carries social risk. The kibun of open challenge feels threatening. And the student who went red has had their chemyeon damaged in front of peers. You pause the seminar, restructure it: ideas are submitted in writing first, then discussed anonymously. You build toward named discussion over several sessions. The class re-engages.",
      withoutUnderstanding: "You push through, encouraging students to 'be braver' and 'take intellectual risks.' The more you push, the quieter the room gets. You write in your reflection that the class lacks critical thinking skills. The students go home and tell their parents the class is uncomfortable.",
    },
    {
      id: 'korea-review-2',
      title: 'The Departure and the New Teacher',
      termsInPlay: ['jeong', 'gongbu', 'kibun'],
      situation: "You are a new teacher taking over a class mid-year from a highly loved teacher who left unexpectedly. Several parents are formally polite but cool in meetings. One student's homework completion has dropped from 95% to 60%. At your first parent meeting, you share progress data and the room feels flat despite your warmth and preparation.",
      withUnderstanding: "You understand that jeong for your predecessor has not transferred to you yet \u2014 it takes time and cannot be rushed. The cool kibun in the room is not rejection; it's grief. The student's gongbu drop is emotional, not motivational. You spend the first meetings listening more than presenting, acknowledging the transition explicitly, and building small moments of connection rather than asserting authority through data.",
      withoutUnderstanding: "You interpret the flat meetings as a difficult parent cohort and the homework drop as a discipline issue. You tighten expectations and send formal notes. The parents compare notes with each other. Several request a meeting with the principal to discuss the new teacher.",
    },
  ],
}
