export const koreaCulturalVocab = {
  id: 'korea-cultural-001',
  country: 'South Korea',
  title: 'Korea: Five Cultural Terms',
  subtitle: 'Korean concepts that shape how students read rooms, how families protect dignity, and how relationships hold weight.',
  estimatedMinutes: 10,
  difficulty: 'foundational',
  type: 'cultural_vocab',
  facilitatorNote: "The Korea module already uses the word hagwon. These five terms go deeper into the social and relational logic that sits beneath academic pressure \u2014 the invisible operating system that teachers often sense but struggle to name.",
  cards: [
    {
      id: 'nunchi',
      term: 'Nunchi',
      script: '\ub208\uce58',
      pronunciation: 'NOON-chee',
      literalTranslation: 'social reading ability / reading the room',
      learnerFriendlyDefinition: "The ability to accurately read unspoken social cues, emotional atmosphere, and others\u2019 unexpressed expectations \u2014 without being told. A core social competence that Koreans develop from childhood.",
      whyItMatters: "A student with strong nunchi adjusts their behaviour before a teacher intervenes. A teacher with strong nunchi is respected; one who misses obvious signals is seen as cold or unaware. A quiet, self-correcting classroom is not passivity \u2014 it is nunchi in action.",
      schoolExample: "A teacher\u2019s tone shifts slightly when a student\u2019s answer goes in the wrong direction. Every other student recalibrates. The student who gave the answer does not \u2014 and keeps elaborating. The class registers this as a nunchi failure.",
      watchFor: "Students who self-regulate before being asked. Group dynamics that shift in response to teacher mood without any words being exchanged. Peer pressure that enforces conformity silently.",
      contexts: ['students', 'classroom', 'social dynamics'],
    },
    {
      id: 'chemyeon',
      term: 'Chemyeon',
      script: '\uccb4\uba74',
      pronunciation: 'cheh-MYUN',
      literalTranslation: 'social face / dignity',
      learnerFriendlyDefinition: "Social face \u2014 the publicly maintained dignity that comes from fulfilling one\u2019s role appropriately, achieving socially visible success, and avoiding public embarrassment. Korea\u2019s version of face, distinct from the Chinese concept of mianzi.",
      whyItMatters: "Chemyeon is lost through public correction, academic failure in visible settings, or being associated with failure. A student who cannot recover their chemyeon after a public stumble may disengage entirely rather than risk further loss. Parents whose child is criticised at a meeting feel their own chemyeon is implicated.",
      schoolExample: "A teacher corrects a student\u2019s grammar in front of the class, expecting this to be a learning moment. The student goes quiet for the rest of the week. Their chemyeon was damaged and they have no strategy for recovering it in this setting.",
      watchFor: "Withdrawal after visible failure. Students who refuse to attempt tasks they might get wrong publicly. Parents who respond to feedback as if they personally have been criticised.",
      contexts: ['students', 'parents', 'feedback'],
    },
    {
      id: 'kibun',
      term: 'Kibun',
      script: '\uae30\ubd84',
      pronunciation: 'KEE-boon',
      literalTranslation: 'mood / emotional atmosphere',
      learnerFriendlyDefinition: "The prevailing emotional mood or atmosphere of an interaction \u2014 something that can be maintained, disrupted, or gradually restored. Good kibun keeps a conversation productive; disrupted kibun may end real communication even if the conversation continues on the surface.",
      whyItMatters: "Skilled navigators of Korean social settings read kibun continuously and adjust \u2014 pausing, softening, or redirecting when the atmosphere shifts. Teachers who monitor kibun can navigate parent-teacher conversations more effectively than those who push through regardless of emotional climate.",
      schoolExample: "A parent meeting is going well. The teacher introduces a concern about attendance too directly. The parent\u2019s kibun shifts \u2014 they become politely non-committal for the rest of the meeting. The teacher thinks the point landed. It did not.",
      watchFor: "Sudden polite vagueness after a direct comment. Nodding that does not translate into agreement or follow-through. The moment the energy in a meeting changes and the other person becomes formal.",
      contexts: ['parents', 'communication', 'meetings'],
    },
    {
      id: 'jeong',
      term: 'Jeong',
      script: '\uc815',
      pronunciation: 'JUNG',
      literalTranslation: 'relational bond / attachment',
      learnerFriendlyDefinition: "A deep emotional connection formed through time and shared experience \u2014 not romantic, but warm, loyal, and hard to articulate. Jeong accumulates slowly and is felt as a genuine loss when severed.",
      whyItMatters: "Teachers who stay at a school for years build jeong with families. Students who have been genuinely supported through difficulty feel jeong toward those teachers. This explains why relationship consistency matters enormously in Korean school communities \u2014 and why transitions and teacher changes are felt as real losses, not just administrative inconveniences.",
      schoolExample: "A beloved Year 4 teacher leaves at the end of the year. Several families send extended farewell messages. One writes: 'our son has not stopped talking about this.' This is jeong \u2014 not sentiment, but a genuine relational bond being severed.",
      watchFor: "Disproportionate responses to teacher departures. Students who maintain unusual loyalty to particular teachers over years. The weight families give to long-term relational continuity with specific staff.",
      contexts: ['relationships', 'transitions', 'parents'],
    },
    {
      id: 'gongbu',
      term: 'Gongbu',
      script: '\uacf5\ubd80',
      pronunciation: 'GONG-boo',
      literalTranslation: 'study / diligent learning',
      learnerFriendlyDefinition: "Study and learning understood as a cultural virtue and moral duty \u2014 not merely an academic activity. Gongbu is an identity, not a task. A student who does gongbu is becoming the right kind of person.",
      whyItMatters: "A student who is not studying diligently is not simply underperforming academically \u2014 they are failing a cultural obligation to their family and themselves. This explains the weight Korean families attach to academic concern, and why 'they\u2019re not working to their potential' can land as a character indictment, not a progress note.",
      schoolExample: "A teacher tells a parent that their son is bright but not putting in consistent effort. The parent\u2019s reaction is more intense than the teacher expected. In their frame, the issue is not academic performance \u2014 it is whether their child is becoming the kind of person who does gongbu.",
      watchFor: "Extreme parental investment in effort signals, not just attainment. Students who self-identify as hard workers even when outcomes are mixed. The emotional weight parents give to conversations about effort specifically.",
      contexts: ['parents', 'students', 'effort'],
    },
  ],
}
