export const ksaCulturalVocab = {
  id: 'ksa-cultural-001',
  country: 'Kingdom of Saudi Arabia',
  title: 'Saudi Arabia: Five Cultural Terms',
  subtitle: 'Arabic and Islamic concepts that shape how families think, communicate, and navigate school.',
  estimatedMinutes: 10,
  difficulty: 'foundational',
  type: 'cultural_vocab',
  facilitatorNote: "These terms come from inside the culture. You don't need to speak Arabic to use them — but recognising them changes how you read everyday school interactions. Each card focuses on a concept that has no clean English equivalent and that regularly shapes parent, student, and colleague behaviour in Saudi school settings.",
  cards: [
    {
      id: 'wasta',
      term: 'Wasta',
      script: '\u0648\u0627\u0633\u0637\u0629',
      pronunciation: 'WAH-stah',
      literalTranslation: 'intermediary / connections',
      learnerFriendlyDefinition: "Using personal connections or a trusted third party to facilitate outcomes in institutional settings. A request made through someone the school already knows carries more weight than the same request made directly.",
      whyItMatters: "Parents may not approach a teacher or principal without first establishing \u2014 or activating \u2014 a relational connection. What looks like an unusual access route is often a culturally normal influence mechanism, not an attempt to bypass process.",
      schoolExample: "A mother asks a family friend who knows the head of year to pass along her concern about her daughter\u2019s grouping. She is not going behind anyone\u2019s back \u2014 she is using the most effective channel she knows.",
      watchFor: "Unusual access, warm introductions from unexpected sources, or requests that arrive through a third party rather than directly.",
      contexts: ['parents', 'leadership', 'communication'],
    },
    {
      id: 'izzah',
      term: 'Izzah',
      script: '\u0627\u0644\u0639\u0632\u0629',
      pronunciation: 'IZ-zah',
      literalTranslation: 'honour / dignity',
      learnerFriendlyDefinition: "God-granted human dignity that extends to family standing in the community. A fundamental Islamic concept of honour that shapes how feedback is given, received, and remembered.",
      whyItMatters: "What reads to a teacher as a clinical observation about a child\u2019s progress can land as a dignity wound. Izzah explains why some parents respond to feedback with unexpected force, or why certain conversations must be private, warm, and face-preserving.",
      schoolExample: "A teacher matter-of-factly reports that a child is falling behind in front of another parent. The family does not return calls for two weeks. The teacher thinks the meeting went fine; the parent felt their izzah was publicly damaged.",
      watchFor: "Unexpected withdrawal after feedback. A parent\u2019s request that conversations stay private. Reluctance to acknowledge struggle in group settings.",
      contexts: ['parents', 'feedback', 'communication'],
    },
    {
      id: 'haya',
      term: 'Haya',
      script: '\u062d\u064a\u0627\u0621',
      pronunciation: 'HAH-yah',
      literalTranslation: 'modesty / shyness as virtue',
      learnerFriendlyDefinition: "A valued Islamic character trait \u2014 reticence, restraint, and modesty as expressions of good character. Not timidity, but a deliberate orientation toward humility and propriety.",
      whyItMatters: "Students demonstrating haya may not volunteer answers, raise their hand when unsure, or speak directly with a teacher about personal matters. This is not disengagement \u2014 it is a performance of virtue that can be invisible to teachers expecting assertive participation.",
      schoolExample: "A Year 6 girl consistently declines to answer questions in front of male classmates. Her teacher interprets this as lack of confidence. The student sees it as proper conduct.",
      watchFor: "Selective silence, reluctance to speak publicly, or indirect communication from otherwise engaged students.",
      contexts: ['students', 'classroom', 'participation'],
    },
    {
      id: 'amana',
      term: 'Amana',
      script: '\u0623\u0645\u0627\u0646\u0629',
      pronunciation: 'ah-MAH-nah',
      literalTranslation: 'sacred trust / trusteeship',
      learnerFriendlyDefinition: "The concept that those entrusted with something \u2014 including a child \u2014 hold it in trust on behalf of God. Teachers are not just educators; they are custodians of a family\u2019s most valued amana.",
      whyItMatters: "This frames the intensity of parental expectation as moral rather than simply personal. When something goes wrong at school, it may feel like a sacred trust has been broken \u2014 not just an institutional failure.",
      schoolExample: "A father responds to a safeguarding conversation with unusual gravity. A Western teacher may find the reaction disproportionate to what seemed like a minor incident. The father is responding through amana: his child was left vulnerable in a space he entrusted.",
      watchFor: "Heightened parental concern around anything involving the child\u2019s safety, wellbeing, or moral environment. The intensity reflects the nature of the trust, not simply the severity of the event.",
      contexts: ['parents', 'safeguarding', 'accountability'],
    },
    {
      id: 'sabr',
      term: 'Sabr',
      script: '\u0635\u0628\u0631',
      pronunciation: 'SAH-br',
      literalTranslation: 'patient endurance',
      learnerFriendlyDefinition: "A core Islamic virtue: the patient, dignified endurance of difficulty without complaint. Practiced sabr means withholding grievance, trusting in a higher order, and waiting rather than acting impulsively.",
      whyItMatters: "A parent practicing sabr may say nothing for weeks while a concern grows. When they finally raise it, the urgency and intensity can feel sudden and disproportionate to a teacher who was unaware anything was wrong. The escalation is not volatility \u2014 it is the end of a long, deliberate restraint.",
      schoolExample: "A mother does not mention that her son has been upset about a seating arrangement for six weeks. At the term review, she raises it as her first concern. The teacher is surprised; the mother has been practicing sabr and finally decided enough time had passed.",
      watchFor: "Concerns raised late but with high intensity. Patience that converts suddenly into urgency. Reading this as overreaction misses the cultural context.",
      contexts: ['parents', 'communication', 'conflict'],
    },
  ],
}
