export const ksaCulturalVocab = {
  id: 'ksa-cultural-001',
  country: 'Kingdom of Saudi Arabia',
  title: 'Saudi Arabia: Five Cultural Terms',
  subtitle: 'Arabic and Islamic concepts that shape how families think, communicate, and navigate school.',
  estimatedMinutes: 15,
  difficulty: 'foundational',
  type: 'cultural_vocab',
  facilitatorNote: "These terms come from inside the culture. You don't need to speak Arabic to use them — but recognising them changes how you read everyday school interactions. Each card focuses on a concept that has no clean English equivalent and that regularly shapes parent, student, and colleague behaviour in Saudi school settings.",
  cards: [
    {
      id: 'wasta',
      term: 'Wasta',
      script: '\u0648\u0627\u0633\u0637\u0629',
      pronunciation: 'WAH-stah',
      literalTranslation: 'intermediary / connections',
      learnerFriendlyDefinition: "Using personal connections or a trusted third party to facilitate outcomes in institutional settings. A request made through someone the school already knows carries more weight than the same request made directly.",
      whyItMatters: "Parents may not approach a teacher or principal without first establishing \u2014 or activating \u2014 a relational connection. What looks like an unusual access route is often a culturally normal influence mechanism, not an attempt to bypass process.",
      schoolExample: "A mother asks a family friend who knows the head of year to pass along her concern about her daughter's grouping. She is not going behind anyone's back \u2014 she is using the most effective channel she knows.",
      watchFor: "Unusual access, warm introductions from unexpected sources, or requests that arrive through a third party rather than directly.",
      contexts: ['parents', 'leadership', 'communication'],
      cardScenario: {
        situation: "A parent you have never spoken with directly sends you a warm email mentioning that they know the school counsellor personally and wanted to reach out before the term review.",
        withUnderstanding: "You recognise this as wasta \u2014 the parent is establishing a relational bridge before making a request. You respond warmly and treat this as a legitimate introduction. The follow-up conversation is productive because trust is already in place.",
        withoutUnderstanding: "You reply formally, note that the counsellor should not be involved in classroom matters, and suggest the parent use the standard contact form. The parent feels rebuffed. They do not raise their concern again.",
      },
    },
    {
      id: 'izzah',
      term: 'Izzah',
      script: '\u0627\u0644\u0639\u0632\u0629',
      pronunciation: 'IZ-zah',
      literalTranslation: 'honour / dignity',
      learnerFriendlyDefinition: "God-granted human dignity that extends to family standing in the community. A fundamental Islamic concept of honour that shapes how feedback is given, received, and remembered.",
      whyItMatters: "What reads to a teacher as a clinical observation about a child's progress can land as a dignity wound. Izzah explains why some parents respond to feedback with unexpected force, or why certain conversations must be private, warm, and face-preserving.",
      schoolExample: "A teacher matter-of-factly reports that a child is falling behind in front of another parent. The family does not return calls for two weeks. The teacher thinks the meeting went fine; the parent felt their izzah was publicly damaged.",
      watchFor: "Unexpected withdrawal after feedback. A parent's request that conversations stay private. Reluctance to acknowledge struggle in group settings.",
      contexts: ['parents', 'feedback', 'communication'],
      cardScenario: {
        situation: "You call a parent to discuss their son's reading levels. They answer and you can hear relatives in the background \u2014 you are on speaker phone without knowing it.",
        withUnderstanding: "You keep the feedback warm, general, and strengths-first. You say you'd love to share more detail and ask if there's a better time for a private call. The parent appreciates the discretion and calls back.",
        withoutUnderstanding: "You deliver detailed concerns about the child's reading struggles. The parent becomes defensive and later makes a formal complaint. You are surprised \u2014 the concerns were accurate and well-intentioned.",
      },
    },
    {
      id: 'haya',
      term: 'Haya',
      script: '\u062d\u064a\u0627\u0621',
      pronunciation: 'HAH-yah',
      literalTranslation: 'modesty / shyness as virtue',
      learnerFriendlyDefinition: "A valued Islamic character trait \u2014 reticence, restraint, and modesty as expressions of good character. Not timidity, but a deliberate orientation toward humility and propriety.",
      whyItMatters: "Students demonstrating haya may not volunteer answers, raise their hand when unsure, or speak directly with a teacher about personal matters. This is not disengagement \u2014 it is a performance of virtue that can be invisible to teachers expecting assertive participation.",
      schoolExample: "A Year 6 girl consistently declines to answer questions in front of male classmates. Her teacher interprets this as lack of confidence. The student sees it as proper conduct.",
      watchFor: "Selective silence, reluctance to speak publicly, or indirect communication from otherwise engaged students.",
      contexts: ['students', 'classroom', 'participation'],
      cardScenario: {
        situation: "A strong student \u2014 articulate in written work and confident in small group settings \u2014 rarely speaks in whole-class discussions and never volunteers an answer.",
        withUnderstanding: "You recognise this as haya and build in alternative participation routes: written responses, pair-shares, and small group work. Her engagement and quality are high. You reflect this positively in your assessment of her contributions.",
        withoutUnderstanding: "You mark her participation grade down and note 'needs to build confidence speaking in class' in her report. The family is confused and slightly offended. They know their daughter is highly capable.",
      },
    },
    {
      id: 'amana',
      term: 'Amana',
      script: '\u0623\u0645\u0627\u0646\u0629',
      pronunciation: 'ah-MAH-nah',
      literalTranslation: 'sacred trust / trusteeship',
      learnerFriendlyDefinition: "The concept that those entrusted with something \u2014 including a child \u2014 hold it in trust on behalf of God. Teachers are not just educators; they are custodians of a family's most valued amana.",
      whyItMatters: "This frames the intensity of parental expectation as moral rather than simply personal. When something goes wrong at school, it may feel like a sacred trust has been broken \u2014 not just an institutional failure.",
      schoolExample: "A father responds to a safeguarding conversation with unusual gravity. A Western teacher may find the reaction disproportionate to what seemed like a minor incident. The father is responding through amana: his child was left vulnerable in a space he entrusted.",
      watchFor: "Heightened parental concern around anything involving the child's safety, wellbeing, or moral environment. The intensity reflects the nature of the trust, not simply the severity of the event.",
      contexts: ['parents', 'safeguarding', 'accountability'],
      cardScenario: {
        situation: "A minor playground incident occurs. You resolve it with the students involved and consider it closed. Two days later the father calls the principal, upset that no one contacted him.",
        withUnderstanding: "You understand that from the father's perspective, his child was in your care \u2014 his amana \u2014 and anything that affected her wellbeing required a communication, however minor. You apologise, explain your process, and add a brief incident notification step going forward.",
        withoutUnderstanding: "You explain that the incident was minor and fully resolved. The father escalates further. You feel the reaction is disproportionate. The relationship does not recover.",
      },
    },
    {
      id: 'sabr',
      term: 'Sabr',
      script: '\u0635\u0628\u0631',
      pronunciation: 'SAH-br',
      literalTranslation: 'patient endurance',
      learnerFriendlyDefinition: "A core Islamic virtue: the patient, dignified endurance of difficulty without complaint. Practiced sabr means withholding grievance, trusting in a higher order, and waiting rather than acting impulsively.",
      whyItMatters: "A parent practicing sabr may say nothing for weeks while a concern grows. When they finally raise it, the urgency and intensity can feel sudden and disproportionate to a teacher who was unaware anything was wrong. The escalation is not volatility \u2014 it is the end of a long, deliberate restraint.",
      schoolExample: "A mother does not mention that her son has been upset about a seating arrangement for six weeks. At the term review, she raises it as her first concern. The teacher is surprised; the mother has been practicing sabr and finally decided enough time had passed.",
      watchFor: "Concerns raised late but with high intensity. Patience that converts suddenly into urgency. Reading this as overreaction misses the cultural context.",
      contexts: ['parents', 'communication', 'conflict'],
      cardScenario: {
        situation: "At a term review meeting, a parent raises a specific, detailed concern about their child's friendship group. You had no idea there was an issue. They seem very serious about something that has apparently been ongoing for months.",
        withUnderstanding: "You take the concern seriously, ask how long this has been on their mind, and thank them genuinely for bringing it now. You understand that raising it at all was a decision they held off on deliberately. You make a concrete plan.",
        withoutUnderstanding: "You ask, somewhat defensively, why they didn't mention it sooner. The parent feels their restraint was used against them and that you are deflecting responsibility. They leave the meeting without confidence anything will change.",
      },
    },
  ],
  reviewScenarios: [
    {
      id: 'ksa-review-1',
      title: 'The Late-Term Escalation',
      termsInPlay: ['sabr', 'wasta', 'izzah'],
      situation: "A mother who has been polite and largely absent from school contact all year suddenly calls the principal and mentions that someone she knows on the school board has raised the same concerns she has. She is calm but very clear. The issue: her daughter has been overlooked for the lead in the school performance. She has been watching this situation develop for two months.",
      withUnderstanding: "You recognise all three terms operating at once. The mother practiced sabr until the situation required action. She then activated wasta \u2014 connecting through someone with influence. And the performance lead was not just a role \u2014 it was an izzah event, visible to the whole community. You meet with her privately, acknowledge the concern seriously, and explain the selection process with care. Even if the decision stands, the conversation is handled with dignity.",
      withoutUnderstanding: "You feel the contact through the board member was inappropriate and say so. You defend the selection process efficiently and end the meeting quickly. The mother does not feel heard. The izzah wound is unaddressed. She shares her experience with other families.",
    },
    {
      id: 'ksa-review-2',
      title: 'The Quiet Student and the Participation Grade',
      termsInPlay: ['haya', 'amana', 'izzah'],
      situation: "End-of-term reports go home. A Year 6 girl \u2014 one of your strongest writers \u2014 receives a low participation grade. Her parents request an urgent meeting. They are not angry, but they are very serious. They bring the report, highlighted.",
      withUnderstanding: "You recognise the collision: your participation rubric was built for a Western expressiveness norm. Haya shaped this student's behaviour all term. You acknowledge that your assessment didn't capture her real engagement, revise your approach going forward, and in this meeting treat the family with the gravity they are bringing \u2014 their daughter's izzah is in the report, and they are protecting it. You also understand they feel you didn't hold their amana fully: you missed who she was.",
      withoutUnderstanding: "You explain that participation means speaking in class and that all students are expected to contribute verbally. The parents nod and leave. The daughter's engagement drops the following term. She has learned that the teacher's classroom is not a safe space for the person she is.",
    },
  ],
}
