-- Phase 1 quiz tables and seed
-- Run AFTER 20260330_create_pd_layer.sql

-- ── Table ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pd_quiz_questions (
  id               text PRIMARY KEY,
  module_id        text NOT NULL,
  quiz_type        text NOT NULL CHECK (quiz_type IN ('checkpoint', 'final_exam')),
  dimension_number integer,
  prompt           text NOT NULL,
  options          jsonb NOT NULL,
  sort_order       integer DEFAULT 0
);

ALTER TABLE public.pd_quiz_questions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon read quiz questions" ON public.pd_quiz_questions;
CREATE POLICY "anon read quiz questions" ON public.pd_quiz_questions
  FOR SELECT USING (true);

-- ── Seed ──────────────────────────────────────────────────────────────────

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('china-d1-q1', 'china-001', 'checkpoint', 1, 'During curriculum night, a parent says, "I can see the concepts, but where is the fluency?" In this module, what is the strongest first interpretation?', '[{"id":"a","text":"She is rejecting deep understanding and wants a traditional classroom instead.","isCorrect":false,"feedback":"Too narrow. Li''s work suggests repetition and diligence may be understood as one route to secure mastery, not as the opposite of understanding.","research":["Li (2005)"]},{"id":"b","text":"She may be trying to protect rigor through a different model of what secure learning looks like.","isCorrect":true,"feedback":"Yes. The most useful reading is that the parent is operating with a different theory of how serious learning is built and recognized.","research":["Li (2005)"]},{"id":"c","text":"She mostly wants more visible work because busier homework always means better learning.","isCorrect":false,"feedback":"Distrust can appear, but that is not the strongest first interpretation from the research base.","research":["Li (2005)","Ran (2001)"]}]'::jsonb, 1)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('china-d2-q1', 'china-001', 'checkpoint', 2, 'A parent has studied your unit overview, tabbed a supplemental workbook to match it, and offers it to you before school. What is the best default reading?', '[{"id":"a","text":"The parent is trying to become a co-designer of your curriculum and should be read mainly as overstepping.","isCorrect":false,"feedback":"That may be how it feels, but Ran''s ''parallel tracks'' framing suggests the parent may instead be offering what they understand as partnership.","research":["Ran (2001)"]},{"id":"b","text":"The parent may be trying to collaborate through a different model of school-home partnership.","isCorrect":true,"feedback":"Yes. This is the core interpretive move in the China module.","research":["Ran (2001)"]},{"id":"c","text":"The parent is signaling that she has already given up on the school''s approach and will run a separate system at home.","isCorrect":false,"feedback":"Possible, but less research-grounded as the starting assumption here.","research":["Ran (2001)","Guo, Wu, and Liu (2019)"]}]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('china-d3-q1', 'china-001', 'checkpoint', 3, 'A parent says, "He understands it, but he still needs more practice to be solid." Why can that line feel educationally reasonable in this context?', '[{"id":"a","text":"Because more pages automatically prove the school is better.","isCorrect":false,"feedback":"Volume can act as a signal, but the deeper issue is visible seriousness and secure mastery.","research":["Li (2005)"]},{"id":"b","text":"Because practice can signal seriousness and help make mastery feel more secure and visible.","isCorrect":true,"feedback":"Yes. This links homework to a theory of learning rather than to busyness alone.","research":["Li (2005)","Ran (2001)"]},{"id":"c","text":"Because parents in this context usually see inquiry as unserious compared with traditional learning.","isCorrect":false,"feedback":"Too broad and stereotyped. The stronger research claim is about different assumptions of rigor.","research":["Li (2005)"]}]'::jsonb, 3)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('china-final-q1', 'china-001', 'final_exam', NULL, 'A parent asks publicly in WeChat why your class gives less homework than another class. What is the best first move?', '[{"id":"a","text":"Reply sharply so the group sees you are in charge.","isCorrect":false,"feedback":"This protects face but usually misses the real issue: parents are testing whether standards are legible and trustworthy.","research":["Guo, Wu, and Liu (2019)"]},{"id":"b","text":"Acknowledge the concern briefly, explain the logic of workload, and move the deeper conversation into a structured channel.","isCorrect":true,"feedback":"Yes. This preserves professionalism without treating the parent question as pure defiance.","research":["Guo, Wu, and Liu (2019)","Ran (2001)"]},{"id":"c","text":"Ignore it so you do not reward public criticism.","isCorrect":false,"feedback":"Ignoring it can push families to rely even more on the parent network for interpretation.","research":["Guo, Wu, and Liu (2019)"]}]'::jsonb, 1)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('china-final-q2', 'china-001', 'final_exam', NULL, 'Which statement best captures the ''parallel tracks'' problem?', '[{"id":"a","text":"Parents and teachers want different outcomes for the child.","isCorrect":false,"feedback":"Not usually. Ran''s point is that they may want the same outcome while misreading each other''s signals.","research":["Ran (2001)"]},{"id":"b","text":"Parents and teachers may pursue the same goal while misreading each other''s signs of support and seriousness.","isCorrect":true,"feedback":"Yes. That is the core insight of the China module.","research":["Ran (2001)"]},{"id":"c","text":"Teachers should always give parents what they ask for to stay relational.","isCorrect":false,"feedback":"The goal is not automatic accommodation. It is clearer interpretation and cleaner boundaries.","research":["Ran (2001)"]}]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('china-final-q3', 'china-001', 'final_exam', NULL, 'A student is quiet but attentive, and the parent says this is respectful listening. A culturally intelligent teacher should:', '[{"id":"a","text":"Treat the parent explanation as an excuse and insist the child participate more immediately.","isCorrect":false,"feedback":"That risks turning a participation norm into a character verdict.","research":["Li (2005)"]},{"id":"b","text":"Recognize the parent''s model, then explain participation as a school-taught skill with support structures.","isCorrect":true,"feedback":"Yes. This bridges models instead of ranking them.","research":["Li (2005)"]},{"id":"c","text":"Avoid the topic entirely so the family does not feel criticized.","isCorrect":false,"feedback":"Avoidance often creates a later trust problem when report comments or assessments surface the issue anyway.","research":["Ran (2001)"]}]'::jsonb, 3)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('korea-d1-q1', 'korea-001', 'checkpoint', 1, 'A parent expects the homeroom teacher to understand the child''s wider learning situation, not just classroom performance. What is the best explanation?', '[{"id":"a","text":"Because Korean parents are unusually dependent on school adults.","isCorrect":false,"feedback":"Too crude. The stronger explanation is institutional: the homeroom role has historically carried relational and moral weight.","research":["Jung (2014)"]},{"id":"b","text":"Because the homeroom role has historically involved affective care and guidance, not just instruction.","isCorrect":true,"feedback":"Yes. This helps explain why families may imagine the homeroom teacher as a central adult in the child''s development.","research":["Jung (2014)"]},{"id":"c","text":"Because once a child has academy support, the school teacher is naturally expected to manage that whole system too.","isCorrect":false,"feedback":"Some parents may hope for coordination, but that is not the primary explanation of the homeroom role itself.","research":["Jung (2014)","Howard (2021)"]}]'::jsonb, 1)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('korea-d2-q1', 'korea-001', 'checkpoint', 2, 'A parent coalition pushes back when a test week is replaced by a project week. What is the most research-backed first interpretation?', '[{"id":"a","text":"They are mainly uncomfortable with innovation and need more modern pedagogy explained to them.","isCorrect":false,"feedback":"That misses the meritocratic logic Jang describes. Parent activism can reflect a defense of legible signals and fair positioning.","research":["Jang (2024)"]},{"id":"b","text":"They may be defending competitive legibility and predictability inside a high-stakes system.","isCorrect":true,"feedback":"Yes. This is the strongest interpretive starting point.","research":["Jang (2024)"]},{"id":"c","text":"They are mostly echoing academy culture rather than expressing a school-based concern of their own.","isCorrect":false,"feedback":"Shadow education matters, but this is too reductive to explain parent activism well.","research":["Jang (2024)","Howard (2021)"]}]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('korea-d3-q1', 'korea-001', 'checkpoint', 3, 'A student consistently waits until she is sure an answer is correct before speaking. What is the strongest interpretation?', '[{"id":"a","text":"She mainly lacks confidence and needs stronger encouragement to speak up.","isCorrect":false,"feedback":"Incomplete. Her caution may also be tied to norms of seriousness, exposure, and correctness.","research":["Lee and Kim (2019)"]},{"id":"b","text":"She may be protecting competence in a setting where accuracy carries social and educational weight.","isCorrect":true,"feedback":"Yes. This lets the teacher frame risk-taking as an additional academic skill rather than as a defect.","research":["Lee and Kim (2019)","Howard (2021)"]},{"id":"c","text":"Her family is probably overvaluing marks and causing the whole pattern.","isCorrect":false,"feedback":"Too binary. The student may be navigating systems with different definitions of serious learning.","research":["Lee and Kim (2019)"]}]'::jsonb, 3)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('korea-final-q1', 'korea-001', 'final_exam', NULL, 'A parent asks for broad unit alignment with an academy. Which response shows the best interpretive stance before boundary-setting?', '[{"id":"a","text":"Assume the parent is trying to secure unfair advantage.","isCorrect":false,"feedback":"This skips over the coordination logic that often drives such requests.","research":["Howard (2021)"]},{"id":"b","text":"Recognize the request as an attempt to reduce fragmentation, then explain the school''s fairness boundary clearly.","isCorrect":true,"feedback":"Yes. This is the key move the module is trying to teach.","research":["Howard (2021)"]},{"id":"c","text":"Provide the information casually, then worry about policy later.","isCorrect":false,"feedback":"Short-term helpfulness can create a bigger fairness problem once expectations are established.","research":["Howard (2021)"]}]'::jsonb, 1)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('korea-final-q2', 'korea-001', 'final_exam', NULL, 'What is the best school response when a student is accurate but reluctant to risk being wrong in public?', '[{"id":"a","text":"Treat the problem as lack of resilience and confront it directly.","isCorrect":false,"feedback":"That risks moralizing the behavior instead of teaching a new academic skill.","research":["Lee and Kim (2019)"]},{"id":"b","text":"Create lower-stakes structures that make exploratory participation feel safer and still rigorous.","isCorrect":true,"feedback":"Yes. This is a better bridge between accuracy-oriented seriousness and visible-thinking pedagogy.","research":["Lee and Kim (2019)"]},{"id":"c","text":"Ignore it because correctness matters more than process.","isCorrect":false,"feedback":"That leaves an important learning mismatch untouched.","research":["Lee and Kim (2019)"]}]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('korea-final-q3', 'korea-001', 'final_exam', NULL, 'What principle best captures this module''s approach to parent communication?', '[{"id":"a","text":"More access is always better.","isCorrect":false,"feedback":"Not if it creates invisible labor and inequity.","research":["Jang (2024)"]},{"id":"b","text":"Communication should be structured so that care and clarity are visible without consuming the teacher.","isCorrect":true,"feedback":"Yes. The issue is not whether to communicate, but what channel can carry the relationship sustainably.","research":["Jung (2014)","Jang (2024)"]},{"id":"c","text":"Teachers should avoid parent groups entirely in Korea.","isCorrect":false,"feedback":"The research does not support a universal prohibition.","research":["Jang (2024)"]}]'::jsonb, 3)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('ksa-d1-q1', 'ksa-001', 'checkpoint', 1, 'A parent asks what a ''student voice'' activity will actually teach children to do. What is the strongest first interpretation?', '[{"id":"a","text":"The parent is against critical thinking and modern pedagogy.","isCorrect":false,"feedback":"That misses the core dynamic. The parent may be trying to interpret how the school''s international ethos fits local expectations.","research":["Hammad and Shah (2018)"]},{"id":"b","text":"The parent may be testing how the school''s international ethos fits with local moral and cultural expectations.","isCorrect":true,"feedback":"Yes. This is the dissonance at the center of the KSA module.","research":["Hammad and Shah (2018)"]},{"id":"c","text":"The parent mostly needs the English terminology simplified.","isCorrect":false,"feedback":"Language matters, but the deeper issue is interpretation, not vocabulary alone.","research":["Hammad and Shah (2018)"]}]'::jsonb, 1)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('ksa-d2-q1', 'ksa-001', 'checkpoint', 2, 'In this module, why do routine parent questions sometimes feel larger than they first appear?', '[{"id":"a","text":"Because families are mostly asking for faster updates and tighter logistics.","isCorrect":false,"feedback":"Updates matter, but the research here shows communication is also interpretive work.","research":["Hammad and Shah (2018)"]},{"id":"b","text":"Because communication is often doing interpretive work about what the school means, not just what it is doing.","isCorrect":true,"feedback":"Yes. That is why small questions can carry more weight than they first appear to.","research":["Hammad and Shah (2018)"]},{"id":"c","text":"Because the real problem is usually choosing the wrong communication platform.","isCorrect":false,"feedback":"The medium matters less than the interpretive burden the medium creates.","research":["Hammad and Shah (2018)"]}]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('ksa-d3-q1', 'ksa-001', 'checkpoint', 3, 'Why can an English-first routine become more than a language policy in this setting?', '[{"id":"a","text":"Because students often overreact emotionally to otherwise neutral school routines.","isCorrect":false,"feedback":"This underestimates the social meaning of language hierarchies.","research":["Alsaawi and Almulhim (2024)"]},{"id":"b","text":"Because it can quietly attach prestige, intelligence, or legitimacy to English over Arabic.","isCorrect":true,"feedback":"Yes. That is the central risk the module asks teachers to notice.","research":["Alsaawi and Almulhim (2024)"]},{"id":"c","text":"Because families in this context usually oppose strong English instruction on principle.","isCorrect":false,"feedback":"The evidence points the other way: many families actively value English while still caring deeply about Arabic and identity.","research":["Alothman et al. (2024)","Alsaawi and Almulhim (2024)"]}]'::jsonb, 3)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('ksa-final-q1', 'ksa-001', 'final_exam', NULL, 'A parent asks whether a ''student voice'' activity teaches children to challenge adults more broadly. What is the best first move?', '[{"id":"a","text":"Assume the parent is opposed to agency and defend the school firmly.","isCorrect":false,"feedback":"That turns an interpretive question into a values battle too quickly.","research":["Hammad and Shah (2018)"]},{"id":"b","text":"Explain what the activity concretely involves and what kind of participation it does and does not ask for.","isCorrect":true,"feedback":"Yes. Concrete translation is often better than abstract reassurance.","research":["Hammad and Shah (2018)"]},{"id":"c","text":"Say the school should not have to justify internationally normal practices.","isCorrect":false,"feedback":"That ignores the dissonance the research identifies as endemic to this setting.","research":["Hammad and Shah (2018)"]}]'::jsonb, 1)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('ksa-final-q2', 'ksa-001', 'final_exam', NULL, 'A child begins treating English as the language of status. What is the strongest explanation?', '[{"id":"a","text":"The family must be discouraging Arabic at home.","isCorrect":false,"feedback":"That overlocates the cause in the family and misses the school''s hidden curriculum.","research":["Alsaawi and Almulhim (2024)"]},{"id":"b","text":"The school environment may be teaching a hierarchy of linguistic belonging alongside English growth.","isCorrect":true,"feedback":"Yes. That is the key issue to name and address.","research":["Alsaawi and Almulhim (2024)"]},{"id":"c","text":"This is unavoidable in any international school.","isCorrect":false,"feedback":"It may be common, but it is not inevitable. Design and messaging choices matter.","research":["Alsaawi and Almulhim (2024)"]}]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('ksa-final-q3', 'ksa-001', 'final_exam', NULL, 'What does the Saudi school-choice research suggest about many families in this sector?', '[{"id":"a","text":"They are trying to combine opportunity, English, and pedagogy with cultural and moral fit.","isCorrect":true,"feedback":"Yes. That is the most faithful summary of the research base.","research":["Alothman et al. (2024)","Hammad and Shah (2018)"]},{"id":"b","text":"They are trading away local continuity for future opportunity.","isCorrect":false,"feedback":"That is the wrong binary. Many are actively trying to preserve both.","research":["Alothman et al. (2024)"]},{"id":"c","text":"They mainly choose on prestige and facilities.","isCorrect":false,"feedback":"Those may matter, but they are not the full explanation in this module''s research base.","research":["Alothman et al. (2024)"]}]'::jsonb, 3)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('india-d1-q1', 'india-001', 'checkpoint', 1, 'After a polished exhibition, a parent asks, "But where does my child actually stand?" What is the best first interpretation?', '[{"id":"a","text":"Rejecting holistic education and wanting the school to become more traditional.","isCorrect":false,"feedback":"Too fast. The parent may be asking whether the school''s claims can be translated into recognizable proof.","research":["Ullah, Mukherjee, and Middendorf (2025)"]},{"id":"b","text":"Requesting legible evidence that the school is academically trustworthy.","isCorrect":true,"feedback":"Yes. Trust and legibility are central to the school-choice research in this module.","research":["Ullah, Mukherjee, and Middendorf (2025)","Boruah, Phogat, and Singh (2024)"]},{"id":"c","text":"Trying to pressure the teacher into producing rank because competition is the only thing parents trust.","isCorrect":false,"feedback":"That may happen, but the deeper and more common issue is legibility rather than rank for its own sake.","research":["Ullah, Mukherjee, and Middendorf (2025)"]}]'::jsonb, 1)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('india-d2-q1', 'india-001', 'checkpoint', 2, 'Why do marks remain powerful even in schools that sincerely promote inquiry and narrative feedback?', '[{"id":"a","text":"Because parents are uncomfortable with progressive methods in general.","isCorrect":false,"feedback":"The issue is less dislike of innovation and more the social usefulness of marks as easy, comparable evidence.","research":["Ullah, Mukherjee, and Middendorf (2025)"]},{"id":"b","text":"Because marks are legible, comparable, and widely recognized as signals of seriousness.","isCorrect":true,"feedback":"Yes. That is why removing marks without replacing their legibility creates anxiety.","research":["Ullah, Mukherjee, and Middendorf (2025)","Narwana (2018)"]},{"id":"c","text":"Because narrative feedback cannot carry useful academic information in this context.","isCorrect":false,"feedback":"Narrative feedback can work, but it needs anchors and translation into concrete evidence.","research":["Boruah, Phogat, and Singh (2024)"]}]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('india-d3-q1', 'india-001', 'checkpoint', 3, 'Which PTM outcome is most likely to produce frustration later, even if the meeting felt warm in the moment?', '[{"id":"a","text":"The teacher is respectful but somewhat formal.","isCorrect":false,"feedback":"Tone matters, but the stronger finding is about clarity and visible follow-through.","research":["Boruah, Phogat, and Singh (2024)"]},{"id":"b","text":"They feel heard politely but see little concrete action or specificity afterward.","isCorrect":true,"feedback":"Yes. Warmth without follow-through is one of the clearest risks named in the study.","research":["Boruah, Phogat, and Singh (2024)"]},{"id":"c","text":"The teacher uses some educational vocabulary the parent does not fully recognize.","isCorrect":false,"feedback":"Jargon can be a problem, but it is not the main pattern highlighted in the PTM research.","research":["Boruah, Phogat, and Singh (2024)"]}]'::jsonb, 3)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('india-d4-q1', 'india-001', 'checkpoint', 4, 'What is the main caution about school language such as ''Indian values'' in international-school settings?', '[{"id":"a","text":"They are too politically sensitive to use responsibly at all.","isCorrect":false,"feedback":"The issue is not the phrase alone, but what version of Indianness it quietly privileges.","research":["Babu and Mahajan (2021)"]},{"id":"b","text":"They can sound inclusive while actually centering a selective, classed version of belonging.","isCorrect":true,"feedback":"Yes. This is why specificity and plurality matter in how schools operationalize these values claims.","research":["Babu and Mahajan (2021)","Gurney (2017)"]},{"id":"c","text":"Parents generally treat this language as branding and focus on academics instead.","isCorrect":false,"feedback":"The research suggests values and belonging matter alongside academics, not after them.","research":["Babu and Mahajan (2021)"]}]'::jsonb, 4)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('india-d5-q1', 'india-001', 'checkpoint', 5, 'A high-performing student submits polished work but avoids visible trial-and-error. What is the strongest first interpretation?', '[{"id":"a","text":"The family is clearly pressuring the student too much, and that is the main issue.","isCorrect":false,"feedback":"Pressure may be part of the picture, but the module warns against overdiagnosing the family before understanding the student''s performance logic.","research":["Parikh et al. (2019)","Pienyu, Margaret, and D''Souza (2024)"]},{"id":"b","text":"Potentially protecting competence in a context where mistakes carry weight.","isCorrect":true,"feedback":"Yes. That is why the recommended teacher move is to frame risk-taking as another academic skill, not as a lowering of standards.","research":["Parikh et al. (2019)","Pienyu, Margaret, and D''Souza (2024)"]},{"id":"c","text":"The student is simply better prepared than classmates, so there is no real issue to address.","isCorrect":false,"feedback":"Strong performance does not eliminate the learning costs of overprotection and fear of visible imperfection.","research":["Parikh et al. (2019)"]}]'::jsonb, 5)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('india-d6-q1', 'india-001', 'checkpoint', 6, 'In this module, what is the most useful way to understand parent WhatsApp groups?', '[{"id":"a","text":"Mostly gossip channels that schools should avoid dignifying.","isCorrect":false,"feedback":"The research-backed framing is broader: these groups often act as school-navigation infrastructure.","research":["Ullah, Mukherjee, and Middendorf (2025)","Gurney (2017)"]},{"id":"b","text":"Informal infrastructure for comparison, validation, and uncertainty reduction.","isCorrect":true,"feedback":"Yes. That is why schools need better official clarity rather than pretending the network does not matter.","research":["Ullah, Mukherjee, and Middendorf (2025)","Gurney (2017)"]},{"id":"c","text":"Mainly a sign that parents no longer trust teachers or schools.","isCorrect":false,"feedback":"Distrust may grow through these networks, but their core function is often reassurance and shared interpretation.","research":["Ullah, Mukherjee, and Middendorf (2025)"]}]'::jsonb, 6)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('india-final-q1', 'india-001', 'final_exam', NULL, 'A parent asks for a concrete scorecard after a project exhibition. What is the most research-aligned response?', '[{"id":"a","text":"Explain that marks are outdated and should not matter anymore.","isCorrect":false,"feedback":"This dismisses the parent''s need for trust signals and legibility.","research":["Ullah, Mukherjee, and Middendorf (2025)"]},{"id":"b","text":"Refuse ranking but translate the school''s assessment model into concrete evidence of current performance and next steps.","isCorrect":true,"feedback":"Yes. This is the clearest bridge between school philosophy and parent trust.","research":["Ullah, Mukherjee, and Middendorf (2025)","Boruah, Phogat, and Singh (2024)"]},{"id":"c","text":"Offer a private benchmark only to preserve the relationship.","isCorrect":false,"feedback":"That solves the immediate discomfort while rebuilding a rank culture privately.","research":["Boruah, Phogat, and Singh (2024)"]}]'::jsonb, 1)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('india-final-q2', 'india-001', 'final_exam', NULL, 'What is the best interpretation when a parent asks whether ''Indian Values Week'' includes regional and family differences?', '[{"id":"a","text":"The parent is testing whether the school''s version of Indianness is genuinely plural or selectively polished.","isCorrect":true,"feedback":"Yes. That is exactly the interpretive task behind the question.","research":["Babu and Mahajan (2021)","Gurney (2017)"]},{"id":"b","text":"The parent is derailing a celebration with politics.","isCorrect":false,"feedback":"That misses the legitimate question about belonging and representation.","research":["Babu and Mahajan (2021)"]},{"id":"c","text":"The parent probably just wants more event details.","isCorrect":false,"feedback":"Logistics may be part of it, but this answer misses the values layer.","research":["Babu and Mahajan (2021)"]}]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;

INSERT INTO public.pd_quiz_questions (id, module_id, quiz_type, dimension_number, prompt, options, sort_order)
VALUES ('india-final-q3', 'india-001', 'final_exam', NULL, 'A few parents want a WhatsApp group for clarifications. What is the best guiding principle?', '[{"id":"a","text":"Create a sustainable official clarification structure so the parent network is not the only place where school gets interpreted.","isCorrect":true,"feedback":"Yes. This is the strongest practical lesson from the module''s communication and network dimensions.","research":["Boruah, Phogat, and Singh (2024)","Ullah, Mukherjee, and Middendorf (2025)"]},{"id":"b","text":"Refuse because parent groups are inherently toxic.","isCorrect":false,"feedback":"That treats a structural navigation tool as if it were only a behavioral problem.","research":["Ullah, Mukherjee, and Middendorf (2025)"]},{"id":"c","text":"Join the small group privately and keep things flexible.","isCorrect":false,"feedback":"That may improve short-term responsiveness while weakening equity and sustainability.","research":["Boruah, Phogat, and Singh (2024)"]}]'::jsonb, 3)
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, options = EXCLUDED.options;